### ISSUE TITLE
[Windows] thread 'main' panicked at 'redraw event in non-redraw phase'

### ISSUE THREAD

**Issue by filnet** [rust-windowing/winit#1391]
Hi,

I am seeing this panic when resizing a window (on Windows 10) using master.
I am not seeing it when using winit 0.20.0.

The event loop does mostly nothing and does not invoke window.request_redraw().

```
thread 'main' panicked at 'redraw event in non-redraw phase', C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop\runner.rs:427:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:76
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:60
   3: core::fmt::write
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libcore\fmt\mod.rs:1030
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:64
   6: std::sys_common::backtrace::print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:196
   8: std::panicking::default_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:473
  10: std::panicking::begin_panic<str*>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\panicking.rs:407
  11: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop\runner.rs:427
  12: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop\runner.rs:161
  13: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop\runner.rs:150
  14: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:104
  15: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:680
  16: DefSubclassProc
  17: DefSubclassProc
  18: DispatchMessageW
  19: DispatchMessageW
  20: GetSystemMetrics
  21: KiUserCallbackDispatcher
  22: NtUserMessageCall
  23: GetWindowTextW
  24: GetWindowTextW
  25: GetThemeAppProperties
  26: GetThemeAppProperties
  27: Ordinal119
  28: Ordinal119
  29: GetWindowTextW
  30: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:826
  31: DefSubclassProc
  32: DefSubclassProc
  33: DispatchMessageW
  34: DispatchMessageW
  35: GetSystemMetrics
  36: KiUserCallbackDispatcher
  37: NtUserMessageCall
  38: GetWindowTextW
  39: GetWindowTextW
  40: GetThemeAppProperties
  41: GetThemeAppProperties
  42: Ordinal119
  43: Ordinal119
  44: GetWindowTextW
  45: DispatchMessageW
  46: CallWindowProcW
  47: DefSubclassProc
  48: DefSubclassProc
  49: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:653
  50: DefSubclassProc
  51: DefSubclassProc
  52: DispatchMessageW
  53: DispatchMessageW
  54: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:235
  55: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:192
  56: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\msys64\home\Philippe\rust\winit\src\event_loop.rs:151
  57: winit_gameloop::game_loop::GameLoop::run<closure-0,closure-1,closure-2>
             at .\src\game_loop.rs:52
  58: simple::main
             at .\examples\src\bin\simple.rs:18
  59: std::rt::lang_start::{{closure}}<()>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  60: std::rt::lang_start_internal::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:49
  61: std::panicking::try::do_call<closure-0,i32>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:292
  62: panic_unwind::__rust_maybe_catch_panic
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libpanic_unwind\lib.rs:80
  63: std::panicking::try
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:271
  64: std::panic::catch_unwind
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panic.rs:394
  65: std::rt::lang_start_internal
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:48
  66: std::rt::lang_start<()>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  67: main
  68: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  69: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  70: BaseThreadInitThunk
  71: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\simple.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by filnet** [comment]
I will provide a minimal example that helps reproduce the issue. 
I also have a hunch as to what is causing it.

**Comment by filnet** [comment]
Here is an example that reproduces the issue:

```
use instant::Instant;
use std::time::Duration;
use winit::{
    event::{Event, StartCause, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    simple_logger::init().unwrap();
    let event_loop = EventLoop::new();

    let _window = WindowBuilder::new()
        .with_title("A fantastic window!")
        .build(&event_loop)
        .unwrap();

    let timer_length = Duration::from_millis(10);

    event_loop.run(move |event, _, control_flow| {
        //println!("{:?}", event);

        match event {
            Event::NewEvents(StartCause::Init) => {
                *control_flow = ControlFlow::WaitUntil(Instant::now() + timer_length)
            }
            Event::NewEvents(StartCause::ResumeTimeReached { .. }) => {
                *control_flow = ControlFlow::WaitUntil(Instant::now() + timer_length);
                //println!("\nTimer\n");
            }
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => *control_flow = ControlFlow::Exit,
            _ => (),
        }
    });
}
```

You'll probably notice that it a copy/paste of winit's timer.rs example with:
- the timer_length has been changed from 1s to 10ms
- the println! calls have been commented out
Both changes are important to reproduce the issue as it is timing related.

If you run that example and start resizing you'll eventually get the panic. 
It sometimes panics immediately and sometimes you need to restart it once or twice.
I guess that your result will vary based on your PC specs.

Now for the cause of the panic, I believe it lies in how winit checks if a WaitUntil reached ResumeTimeReached or WaitCancelled.

A first important piece of code is wait_until_time_or_msg:

```
// Returns true if the wait time was reached, and false if a message must be processed.
unsafe fn wait_until_time_or_msg(wait_until: Instant) -> bool {
    let mut msg = mem::zeroed();
    let now = Instant::now();
    if now <= wait_until {
        // MsgWaitForMultipleObjects tends to overshoot just a little bit. We subtract 1 millisecond
        // from the requested time and spinlock for the remainder to compensate for that.
        let resume_reason = winuser::MsgWaitForMultipleObjectsEx(
            0,
            ptr::null(),
            dur2timeout(wait_until - now).saturating_sub(1),
            winuser::QS_ALLEVENTS,
            winuser::MWMO_INPUTAVAILABLE,
        );

        if resume_reason == winerror::WAIT_TIMEOUT {
            while Instant::now() < wait_until {
                if 0 != winuser::PeekMessageW(&mut msg, ptr::null_mut(), 0, 0, 0) {
                    return false;
                }
            }
        }
    }

    return true;
}
```

Here, either a time out occurs or an event happened.
Side note: the returned boolean is not used anywhere...

After wait_until_time_or_msg() is called, new_event() gets called where code like this is found there:

```
                    ControlFlow::WaitUntil(resume_time) => {
                        match Instant::now() >= resume_time {
                            // If the current time is later than the requested resume time, we can tell the
                            // user that the resume time has been reached with `NewEvents` and immdiately move
                            // into event processing.
                            true => {
                                self.call_event_handler(Event::NewEvents(StartCause::ResumeTimeReached {
                                    start: wait_start,
                                    requested_resume: resume_time,
                                }));
                                RunnerState::HandlingEvents
                            },
                            // However, if the current time is EARLIER than the requested resume time, we
                            // don't want to send the `WaitCancelled` event until we know an event is being
                            // sent. Defer.
                            false => RunnerState::DeferredNewEvents(wait_start)
                        }
                    },
```
Here the **current** time is tested against the resume_time to decide if a ResumeTimeReached or a WaitCancelled is underway. But time, as it usually does, continues to run and started out as WaitCancelled is _later_ seen as a ResumeTimeReached. And things probably go awry from then on...

The same **current** time against the resume_time check is done in two other places.

I don't know how to fix this issue without adding some global state (a bool flag) which is ugly.

And again, the issue is reproducible on master only (0.20.0 is fine).

**Comment by aloucks** [comment]
Another way to reproduce it: https://github.com/rust-windowing/winit/issues/1382#issuecomment-573265017

> I don't know how to fix this issue without adding some global state (a bool flag to properly remember what happened) which is ugly.

I think the concept of `now` needs to be constant for the duration of a single turn of the event loop. Perhaps the correct way to fix this will be to replace all uses of `Instant::now()` with a member field on the `EventLoop` (or related struct) that's updated exactly once per tick.

**Comment by filnet** [comment]
Thanks @aloucks for pointing out the similar issue. Was not aware of it.

> I think the concept of now needs to be constant for the duration of a single turn of the event loop. Perhaps the correct way to fix this will be to replace all uses of `Instant::now()` with a member field on the EventLoop (or related struct) that's updated exactly once per tick.

Yes that's another approach I though of too but I think it will lead to a dead end.
The first question, going that route, is where and when to call Instant::now() to capture the current tick time. The best place is probably in or around the wait_until_time_or_msg() function:

```
// Returns true if the wait time was reached, and false if a message must be processed.
unsafe fn wait_until_time_or_msg(wait_until: Instant) -> bool {
    let mut msg = mem::zeroed();
    let now = Instant::now();
    if now <= wait_until {
        // MsgWaitForMultipleObjects tends to overshoot just a little bit. We subtract 1 millisecond
        // from the requested time and spinlock for the remainder to compensate for that.
        let resume_reason = winuser::MsgWaitForMultipleObjectsEx(
            0,
            ptr::null(),
            dur2timeout(wait_until - now).saturating_sub(1),
            winuser::QS_ALLEVENTS,
            winuser::MWMO_INPUTAVAILABLE,
        );

        if resume_reason == winerror::WAIT_TIMEOUT {
            while Instant::now() < wait_until {
                if 0 != winuser::PeekMessageW(&mut msg, ptr::null_mut(), 0, 0, 0) {
                    return false;
                }
            }
        }
    }

    return true;
}
```
A good place for calling `Instant::now()` would right after the call to `MsgWaitForMultipleObjectsEx()`.
But this method, like all wait functions on Windows, will sometimes overshoot. When it happens you, again, run the risk of having `now >=resume_time` and are back to square one.

The `wait_until_time_or_msg()` tries to compensate for overshoots but I don't think the way it is done is reliable.
Why ? Because the default timer resolution on Windows is 15.6 ms and wait functions can overshoot by as much [1]. So the 1ms overshoot compensation looks very suspect.

It is possible to increase the timer resolution up to a max of 1ms. Before you do that first read [2].
The worst part about timer resolution on Windows is that is a global system settings. This means that while you writing code and debugging winit, you might be unknowingly using a high timer resolutions set by another application (a browser or a video player)!

So my takes on a potential fix are:
* accept that `MsgWaitForMultipleObjectsEx()` can overshoot and don't try to compensate for it (1)
* don't rely on calling `Instant::now()` anywhere

At this stage capturing the result of `MsgWaitForMultipleObjectsEx()` and propagating it down sounds like a safer approach. 
But @Osspial might have a better idea.

(1) you might be tempted to query for the current timer resolution and dynamically compensate based on the current value. But keep in mind that the timer resolution can be changed by another application the instant after you queried it.

[1] https://docs.microsoft.com/en-us/windows/win32/sync/wait-functions#wait-functions-and-time-out-intervals
[2] https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/

**Comment by filnet** [comment]
I have what looks like a fix in the pipe. A one liner.
Looks like my previous ramblings were a bit off the mark.

**Comment by filnet** [comment]
Got a panic with the fix:
```
thread 'main' panicked at 'redraw event in non-redraw phase: HandlingEvents', src\platform_impl\windows\event_loop\runner.rs:428:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:84
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\fmt\mod.rs:1025
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:193
   8: std::panicking::default_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:471
  10: std::panicking::begin_panic_handler
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:375
  11: std::panicking::begin_panic_fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:326
  12: winit::platform_impl::platform::event_loop::runner::ELRShared<T>::redraw_events_cleared
  13: winit::platform_impl::platform::event_loop::runner::ELRShared<T>::send_event
  14: winit::platform_impl::platform::event_loop::public_window_callback

````
At least now we know the state the runner was in.
My fixed addresses the case when the runner is in the DeferredNewEvents state.

**Comment by filnet** [comment]
I just pushed an additional fix.

runner::process_events  now handles RedrawRequested events when in the runner is in the HandlingEvents state. They happen so better handle them rather than panicking.

But does not make the runner state machine prettier.
