### ISSUE TITLE
[Windows] unable to run example (panicked at 'assertion failed: `(left == right)` left: `1`, right: `0`)

### ISSUE THREAD

**Issue by AKholetsky** [rust-windowing/winit#1405]
Unable to run window example on Windows 10. (Windows Settings -> Personalization -> colors=Light).

cargo run --example window

```
Finished dev [unoptimized + debuginfo] target(s) in 0.23s
Running `target\debug\examples\window.exe`
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `1`,
right: `0`', src\platform_impl\windows\dark_mode.rs:135:13
stack backtrace:
0:     0x7ff6b813a189 - backtrace::backtrace::trace_unsynchronized
at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
1:     0x7ff6b813a189 - std::sys_common::backtrace::_print_fmt 
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:77
2:     0x7ff6b813a189 - std::sys_common::backtrace::_print::{{impl}}::fmt
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:61
3:     0x7ff6b814ea6b - core::fmt::write
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\fmt\mod.rs:1028
4:     0x7ff6b81377e4 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\io\mod.rs:1412
5:     0x7ff6b813c929 - std::sys_common::backtrace::_print
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:65
6:     0x7ff6b813c929 - std::sys_common::backtrace::print
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:50
7:     0x7ff6b813c929 - std::panicking::default_hook::{{closure}}
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:188
8:     0x7ff6b813c57c - std::panicking::default_hook
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:205
9:     0x7ff6b813d17c - std::panicking::rust_panic_with_hook
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:464
10:     0x7ff6b813ccf0 - std::panicking::continue_panic_fmt
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:373
11:     0x7ff6b813cc34 - std::panicking::begin_panic_fmt
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:328
12:     0x7ff6b80dc7e8 - winit::platform_impl::platform::dark_mode::set_dark_mode_for_window
at E:\Projects\Rust\winit\src\platform_impl\windows\dark_mode.rs:135
13:     0x7ff6b80dc456 - winit::platform_impl::platform::dark_mode::try_dark_mode
at E:\Projects\Rust\winit\src\platform_impl\windows\dark_mode.rs:91
14:     0x7ff6b8083ddd - winit::platform_impl::platform::window::init<()>
at E:\Projects\Rust\winit\src\platform_impl\windows\window.rs:754
15:     0x7ff6b80848c8 - winit::platform_impl::platform::window::Window::new<()>
at E:\Projects\Rust\winit\src\platform_impl\windows\window.rs:72
16:     0x7ff6b807e6e4 - winit::window::WindowBuilder::build<()>
at E:\Projects\Rust\winit\src\window.rs:333
17:     0x7ff6b807c25e - window::main
at E:\Projects\Rust\winit\examples\window.rs:11
18:     0x7ff6b807a2f0 - std::rt::lang_start::{{closure}}<()>
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
19:     0x7ff6b813cb37 - std::rt::lang_start_internal::{{closure}}
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:48
20:     0x7ff6b813cb37 - std::panicking::try::do_call<closure-0,i32>
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:287
21:     0x7ff6b813faf2 - panic_unwind::__rust_maybe_catch_panic
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
22:     0x7ff6b813d4b2 - std::panicking::try
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:265
23:     0x7ff6b813d4b2 - std::panic::catch_unwind
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panic.rs:396
24:     0x7ff6b813d4b2 - std::rt::lang_start_internal
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:47
25:     0x7ff6b807a2cb - std::rt::lang_start<()>
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
26:     0x7ff6b807c3c0 - main
27:     0x7ff6b81529c4 - invoke_main
at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
28:     0x7ff6b81529c4 - __scrt_common_main_seh
at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
29:     0x7ffa93f77bd4 - BaseThreadInitThunk
30:     0x7ffa94ccce71 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\window.exe` (exit code: 101)
```

**Comment by DasEtwas** [comment]
The behaviour for 'SetWindowCompositionAttribute' can be found here: http://www.undoc.airesoft.co.uk/user32.dll/SetWindowCompositionAttribute.php

The assertion at platform_impl/windows/dark_mode.rs implies that the function call may not fail, and also crashed for me.

**Comment by daxpedda** [comment]
It would be good to know what error it is failing on, see this: https://github.com/rust-windowing/winit/pull/1459#discussion_r378839717.

We should be able to figure out why this call is failing.
