### ISSUE TITLE
[Windows] calling request_redraw from thread triggers a panic

### ISSUE THREAD

**Issue by filnet** [rust-windowing/winit#1466]
```
thread 'main' panicked at 'redraw event in non-redraw phase', src\platform_impl\windows\event_loop\runner.rs:427:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:84
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\fmt\mod.rs:1025
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:193
   8: std::panicking::default_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:471
  10: std::panicking::begin_panic<str*>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\panicking.rs:404
  11: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:427
  12: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:161
  13: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:150
  14: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at .\src\platform_impl\windows\event_loop.rs:104
  15: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at .\src\platform_impl\windows\event_loop.rs:680
  16: DefSubclassProc
  17: DefSubclassProc
  18: CallWindowProcW
  19: DispatchMessageW
  20: IsWindowVisible
  21: KiUserCallbackDispatcher
  22: NtUserDispatchMessage
  23: DispatchMessageW
  24: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-1>
             at .\src\platform_impl\windows\event_loop.rs:254
  25: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-1>
             at .\src\platform_impl\windows\event_loop.rs:192
  26: winit::event_loop::EventLoop<()>::run<(),closure-1>
             at .\src\event_loop.rs:148
  27: control_flow::main
             at .\examples\control_flow.rs:55
  28: std::rt::lang_start::{{closure}}<()>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\rt.rs:67
  29: std::rt::lang_start_internal::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:52
  30: std::panicking::try::do_call<closure-0,i32>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:292
  31: panic_unwind::__rust_maybe_catch_panic
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libpanic_unwind\lib.rs:78
  32: std::panicking::try
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:270
  33: std::panic::catch_unwind
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panic.rs:394
  34: std::rt::lang_start_internal
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:51
  35: std::rt::lang_start<()>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\rt.rs:67
  36: main
  37: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  38: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  39: BaseThreadInitThunk
  40: RtlUserThreadStart
```

**Comment by hecrj** [comment]
I can eventually trigger this issue by clicking on the title bar and dragging repeatedly.

**Comment by ennis** [comment]
I can reproduce this issue on winit 0.21.0, Windows 10 18362.295 x64, with the following code (copy-pasted from the docs):
```rust
use winit::window::WindowBuilder;
use winit::event_loop::EventLoop;
use winit::event_loop::ControlFlow;
use winit::event::{Event, WindowEvent};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| {
        // ControlFlow::Wait pauses the event loop if no events are available to process.
        // This is ideal for non-game applications that only update in response to user
        // input, and uses significantly less power/CPU time than ControlFlow::Poll.
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => {
                println!("The close button was pressed; stopping");
                *control_flow = ControlFlow::Exit
            },
            Event::MainEventsCleared => {
                // Application update code.

                // Queue a RedrawRequested event.
                window.request_redraw();
            },
            Event::RedrawRequested(_) => {
                // Redraw the application.
                //
                // It's preferrable to render in this event rather than in MainEventsCleared, since
                // rendering in here allows the program to gracefully handle redraws requested
                // by the OS.
            },
            _ => ()
        }
    });
}
```

 Just clicking the title bar is enough to trigger the panic. Here is the call stack, it that helps:

<details><summary>Call stack</summary>
<p>

```
0: std::sys_common::backtrace::_print::{{impl}}::fmt
             at src\libstd\sys_common\backtrace.rs:59
   1: core::fmt::write
             at src\libcore\fmt\mod.rs:1057
   2: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at src\libstd\io\mod.rs:1426
   3: std::panicking::default_hook::{{closure}}
             at src\libstd\panicking.rs:195
   4: std::panicking::default_hook
             at src\libstd\panicking.rs:215
   5: std::panicking::rust_panic_with_hook
             at src\libstd\panicking.rs:472
   6: std::panicking::begin_panic<str*>
             at src\libstd\panicking.rs:401
   7: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:427
   8: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
             at winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:161
   9: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:150
  10: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at winit-0.21.0\src\platform_impl\windows\event_loop.rs:104
  11: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at winit-0.21.0\src\platform_impl\windows\event_loop.rs:680
  12: DefSubclassProc
  13: DefSubclassProc
  14: CallWindowProcW
  15: DispatchMessageW
  16: IsWindowVisible
  17: KiUserCallbackDispatcher
  18: NtUserMessageCall
  19: GetWindowTextW
  20: MapWindowPoints
  21: IsCompositionActive
  22: Ordinal96
  23: IsCompositionActive
  24: IsCompositionActive
  25: GetWindowTextW
  26: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at winit-0.21.0\src\platform_impl\windows\event_loop.rs:826
  27: DefSubclassProc
  28: DefSubclassProc
  29: CallWindowProcW
  30: DispatchMessageW
  31: IsWindowVisible
  32: KiUserCallbackDispatcher
  33: NtUserMessageCall
  34: GetWindowTextW
  35: MapWindowPoints
  36: IsCompositionActive
  37: Ordinal96
  38: IsCompositionActive
  39: IsCompositionActive
  40: GetWindowTextW
  41: CallWindowProcW
  42: CallWindowProcW
  43: DefSubclassProc
  44: DefSubclassProc
  45: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at winit-0.21.0\src\platform_impl\windows\event_loop.rs:653
  46: DefSubclassProc
  47: DefSubclassProc
  48: CallWindowProcW
  49: DispatchMessageW
  50: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at winit-0.21.0\src\platform_impl\windows\event_loop.rs:235
  51: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at winit-0.21.0\src\platform_impl\windows\event_loop.rs:192
  52: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at winit-0.21.0\src\event_loop.rs:148
  53: scene_info::main
             at .\artifice\examples\scene_info.rs:25
  54: std::rt::lang_start::{{closure}}<()>
             at src\libstd\rt.rs:67
  55: std::panicking::try::do_call<closure-0,i32>
             at src\libstd\panicking.rs:296
  56: panic_unwind::__rust_maybe_catch_panic
             at src\libpanic_unwind\lib.rs:79
  57: std::rt::lang_start_internal
             at src\libstd\rt.rs:51
  58: std::rt::lang_start<()>
             at src\libstd\rt.rs:67
  59: main
  60: __scrt_common_main_seh
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  61: BaseThreadInitThunk
  62: RtlUserThreadStart
```

</p>
</details>

**Comment by simonbuchan** [comment]
@filnet the fixing commit above looks like it will still panic if windows sends a WM_PAINT synchronously at some other time, right?

I'm trying to host [a webview](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2), which will internally add a child window, which seems to cause the event loop to panic with the same stack as this thread from WM_PAINT messages shortly after `IWebView2WebView::put_Bounds()` is called, no matter when that is,

**Comment by simonbuchan** [comment]
@filnet, actually, just tested against your lastest on that branch, and it totally fixes the issue!
