### ISSUE TITLE
[Windows] set_fullscreen panic (0.21)

### ISSUE THREAD

**Issue by alexheretic** [rust-windowing/winit#1469]
Windows 10 panic toggling fullscreen.

## Steps to reproduce
* Checkout latest winit, ie 505f312d5f1ef303e219c3293cf64c8cdb573cd6
* `cargo run --example fullscreen`
* Select either **1** or **2**
* Select monitor _ie 0_
* Toggle out of fullscreen by pressing **f**

```
C:\Users\alex\project\winit>cargo run --example fullscreen
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target\debug\examples\fullscreen.exe`
Please choose the fullscreen mode: (1) exclusive, (2) borderless: 2
Monitor #0: Some("\\\\.\\DISPLAY1")
Please write the number of the monitor to use: 0
Using Some("\\\\.\\DISPLAY1")
thread 'main' panicked at 'already mutably borrowed: BorrowError', src\libcore\result.rs:1188:5
stack backtrace:
   0:     0x7ff7ddd4ee49 - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1:     0x7ff7ddd4ee49 - std::sys_common::backtrace::_print_fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:84
   2:     0x7ff7ddd4ee49 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:61
   3:     0x7ff7ddd63dcb - core::fmt::write
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\fmt\mod.rs:1025
   4:     0x7ff7ddd4c494 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\io\mod.rs:1426
   5:     0x7ff7ddd515e9 - std::sys_common::backtrace::_print
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:65
   6:     0x7ff7ddd515e9 - std::sys_common::backtrace::print
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:50
   7:     0x7ff7ddd515e9 - std::panicking::default_hook::{{closure}}
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:193
   8:     0x7ff7ddd5123c - std::panicking::default_hook
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:210
   9:     0x7ff7ddd51e1c - std::panicking::rust_panic_with_hook
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:471
  10:     0x7ff7ddd519a0 - std::panicking::begin_panic_handler
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:375
  11:     0x7ff7ddd6024d - core::panicking::panic_fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\panicking.rs:84
  12:     0x7ff7ddd6034f - core::result::unwrap_failed
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\result.rs:1188
  13:     0x7ff7ddcfd19f - core::result::Result<core::cell::Ref<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>, core::cell::BorrowError>::expect<core::cell::Ref<core::option::Option<winit::platform_impl::platform::event_loop::runner::
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\result.rs:983
  14:     0x7ff7ddcfa41c - core::cell::RefCell<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>::borrow<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\cell.rs:798
  15:     0x7ff7ddced8e8 - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop\runner.rs:133
  16:     0x7ff7ddc8a3a6 - winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:104
  17:     0x7ff7ddc8b27f - winit::platform_impl::platform::event_loop::public_window_callback<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:770
  18:     0x7ffef074b762 - DefSubclassProc
  19:     0x7ffef074b625 - DefSubclassProc
  20:     0x7fff15da5b6d - CallWindowProcW
  21:     0x7fff15da517c - SendMessageW
  22:     0x7fff15da439b - GetWindowTextW
  23:     0x7fff15da3a5f - MapWindowPoints
  24:     0x7fff1261c58f - IsCompositionActive
  25:     0x7fff1261bff1 - IsCompositionActive
  26:     0x7fff15da3f9f - GetWindowTextW
  27:     0x7fff15da5b6d - CallWindowProcW
  28:     0x7fff15da583e - CallWindowProcW
  29:     0x7ffef074b762 - DefSubclassProc
  30:     0x7ffef074b51c - DefSubclassProc
  31:     0x7ff7ddc8b02b - winit::platform_impl::platform::event_loop::public_window_callback<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:744
  32:     0x7ffef074b762 - DefSubclassProc
  33:     0x7ffef074b625 - DefSubclassProc
  34:     0x7fff15da5b6d - CallWindowProcW
  35:     0x7fff15da573c - DispatchMessageW
  36:     0x7fff15db5000 - MBToWCSEx
  37:     0x7fff1745fe14 - KiUserCallbackDispatcher
  38:     0x7fff152d1524 - NtUserSetWindowPos
  39:     0x7ff7ddce4b9f - winit::platform_impl::platform::window_state::WindowFlags::apply_diff
                               at C:\Users\alex\project\winit\src\platform_impl\windows\window_state.rs:325
  40:     0x7ff7ddd1c386 - winit::platform_impl::platform::window_state::WindowState::set_window_flags<closure-0>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\window_state.rs:141
  41:     0x7ff7ddd18bb0 - winit::platform_impl::platform::window::{{impl}}::set_fullscreen::{{closure}}
                               at C:\Users\alex\project\winit\src\platform_impl\windows\window.rs:484
  42:     0x7ff7ddd08132 - winit::platform_impl::platform::event_loop::EventLoopThreadExecutor::execute_in_thread<closure-0>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:420
  43:     0x7ff7ddc9828a - winit::platform_impl::platform::window::Window::set_fullscreen
                               at C:\Users\alex\project\winit\src\platform_impl\windows\window.rs:396
  44:     0x7ff7ddca3de0 - winit::window::Window::set_fullscreen
                               at C:\Users\alex\project\winit\src\window.rs:622
  45:     0x7ff7ddc9eef7 - fullscreen::main::{{closure}}
                               at C:\Users\alex\project\winit\examples\fullscreen.rs:51
  46:     0x7ff7ddc8a257 - winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:207
  47:     0x7ff7ddd07c03 - alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\liballoc\boxed.rs:1029
  48:     0x7ff7ddcf0236 - winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop\runner.rs:563
  49:     0x7ff7ddd280d6 - std::panic::{{impl}}::call_once<(),closure-0>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\panic.rs:318
  50:     0x7ff7ddd30fcc - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\panicking.rs:292
  51:     0x7ff7ddd54e02 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libpanic_unwind\lib.rs:78
  52:     0x7ff7ddd30eca - std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\panicking.rs:270
  53:     0x7ff7ddd28116 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\panic.rs:394
  54:     0x7ff7ddceffa0 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop\runner.rs:561
  55:     0x7ff7ddcef3fe - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop\runner.rs:437
  56:     0x7ff7ddcee170 - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop\runner.rs:161
  57:     0x7ff7ddcedc11 - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop\runner.rs:150
  58:     0x7ff7ddc8a3a6 - winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:104
  59:     0x7ff7ddc8c118 - winit::platform_impl::platform::event_loop::public_window_callback<()>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:940
  60:     0x7ffef074b762 - DefSubclassProc
  61:     0x7ffef074b625 - DefSubclassProc
  62:     0x7fff15da5b6d - CallWindowProcW
  63:     0x7fff15da5562 - DispatchMessageW
  64:     0x7ff7ddc89e51 - winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:235
  65:     0x7ff7ddc8a2c6 - winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\alex\project\winit\src\platform_impl\windows\event_loop.rs:192
  66:     0x7ff7ddc9d6ed - winit::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\alex\project\winit\src\event_loop.rs:148
  67:     0x7ff7ddc9a901 - fullscreen::main
                               at C:\Users\alex\project\winit\examples\fullscreen.rs:33
  68:     0x7ff7ddc898c0 - std::rt::lang_start::{{closure}}<()>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\rt.rs:67
  69:     0x7ff7ddd517f7 - std::rt::lang_start_internal::{{closure}}
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:52
  70:     0x7ff7ddd517f7 - std::panicking::try::do_call<closure-0,i32>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:292
  71:     0x7ff7ddd54e02 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libpanic_unwind\lib.rs:78
  72:     0x7ff7ddd52152 - std::panicking::try
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:270
  73:     0x7ff7ddd52152 - std::panic::catch_unwind
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panic.rs:394
  74:     0x7ff7ddd52152 - std::rt::lang_start_internal
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:51
  75:     0x7ff7ddc8989b - std::rt::lang_start<()>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\rt.rs:67
  76:     0x7ff7ddc9b670 - main
  77:     0x7ff7ddd67fa4 - invoke_main
                               at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  78:     0x7ff7ddd67fa4 - __scrt_common_main_seh
                               at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  79:     0x7fff172d7bd4 - BaseThreadInitThunk
  80:     0x7fff1742ced1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\fullscreen.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by Imberflur** [comment]
I suspect this is the same issue producing #1400

**Comment by tangmi** [comment]
I can confirm that the issue was introduced in 6a330a2, which is the same commit identified in #1400.

**Comment by yanchith** [comment]
We also ran into this, possibly related: https://github.com/subdgtl/HURBAN-Selector/pull/129
