### ISSUE TITLE
exclusive fullscreen example crashes on exit (ALT-F4) on windows

### ISSUE THREAD

**Issue by jice-nospam** [rust-windowing/winit#1471]
I only reproduce this in exclusive fullscreen mode, not fullscreen borderless or windowed.

```
Please choose the fullscreen mode: (1) exclusive, (2) borderless: 1
Monitor #0: Some("\\\\.\\DISPLAY1")
Please write the number of the monitor to use: 0
Using Some("\\\\.\\DISPLAY1")
[...]
Video mode rust-windowing/glutin#37: 640x480 @ 75 Hz (32 bpp)
[...]
Please write the number of the video mode to use: 37
Using 640x480 @ 75 Hz (32 bpp)
OpenGL version 4.6.0 NVIDIA 432.00
thread 'main' panicked at 'already mutably borrowed: BorrowError', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
[...]
  67: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at h:\jice\cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\event_loop.rs:148
  68: fullscreen::main
             at .\glutin_examples\examples\fullscreen.rs:45
  69: std::rt::lang_start::{{closure}}<()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
  70: std::rt::lang_start_internal::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:48
  71: std::panicking::try::do_call<closure-0,i32>             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:287
  72: panic_unwind::__rust_maybe_catch_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
  73: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:265
  74: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panic.rs:396
  75: std::rt::lang_start_internal
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:47
  76: std::rt::lang_start<()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
  77: main
  78: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  79: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  80: BaseThreadInitThunk
  81: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\fullscreen.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by goddessfreya** [comment]
Dupe: #1400 #1427 #1469
