### ISSUE TITLE
[Windows] Panic on multiple eventloop with multiple windows

### ISSUE THREAD

**Issue by hatoo** [rust-windowing/winit#1585]
https://github.com/hatoo/winit/blob/run_return2/examples/window_run_return2.rs

This code is a modified version of `window_run_return.rs` and demonstrates the issue.

```rust
// Limit this example to only compatible platforms.
#[cfg(any(
    target_os = "windows",
    target_os = "macos",
    target_os = "linux",
    target_os = "dragonfly",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd"
))]
fn main() {
    use std::{thread::sleep, time::Duration};
    use winit::{
        event::{Event, WindowEvent},
        event_loop::{ControlFlow, EventLoop},
        platform::desktop::EventLoopExtDesktop,
        window::WindowBuilder,
    };

    let mut event_loop1 = EventLoop::new();
    let mut event_loop2 = EventLoop::new();

    simple_logger::init().unwrap();
    let _window = WindowBuilder::new()
        .with_title("A fantastic window! 1")
        .build(&event_loop1)
        .unwrap();

    let _window2 = WindowBuilder::new()
        .with_title("A fantastic window! 2")
        .build(&event_loop2)
        .unwrap();

    let mut quit = false;

    while !quit {
        event_loop1.run_return(|event, _, control_flow| {
            *control_flow = ControlFlow::Exit;

            if let Event::WindowEvent { event, .. } = &event {
                // Print only Window events to reduce noise
                println!("{:?}", event);
            }

            match event {
                Event::WindowEvent {
                    event: WindowEvent::CloseRequested,
                    ..
                } => {
                    quit = true;
                }
                Event::MainEventsCleared => {
                    *control_flow = ControlFlow::Exit;
                }
                _ => (),
            }
        });
        event_loop2.run_return(|event, _, control_flow| {
            *control_flow = ControlFlow::Exit;

            if let Event::WindowEvent { event, .. } = &event {
                // Print only Window events to reduce noise
                println!("{:?}", event);
            }

            match event {
                Event::WindowEvent {
                    event: WindowEvent::CloseRequested,
                    ..
                } => {
                    quit = true;
                }
                Event::MainEventsCleared => {
                    *control_flow = ControlFlow::Exit;
                }
                _ => (),
            }
        });
        sleep(Duration::from_millis(16));
        // Sleep for 1/60 second to simulate rendering
        println!("rendering");
    }
}

#[cfg(any(target_os = "ios", target_os = "android", target_arch = "wasm32"))]
fn main() {
    println!("This platform doesn't support run_return.");
}
```

The above code creates 2 windows with separated eventloop and panics on Windows after any input while works fine on macOS. Tested on the master branch.

```
> cargo run --example window_run_return2
   Compiling winit v0.22.2 (C:\Users\hato2\Desktop\winit)
    Finished dev [unoptimized + debuginfo] target(s) in 3.92s
     Running `target\debug\examples\window_run_return2.exe`
KeyboardInput { device_id: DeviceId(DeviceId(0)), input: KeyboardInput { scancode: 0, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: true }
KeyboardInput { device_id: DeviceId(DeviceId(0)), input: KeyboardInput { scancode: 95, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: true }
KeyboardInput { device_id: DeviceId(DeviceId(0)), input: KeyboardInput { scancode: 0, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: true }
KeyboardInput { device_id: DeviceId(DeviceId(0)), input: KeyboardInput { scancode: 98, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: true }
ModifiersChanged((empty))
Focused(false)
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
thread 'main' panicked at 'either event handler is re-entrant (likely), or no event handler is registered (very unlikely)', src\platform_impl\windows\event_loop\runner.rs:235:37
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\panicking.rs:419
  11: core::panicking::panic_fmt
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libcore\panicking.rs:111
  12: core::option::expect_failed
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libcore\option.rs:1260
  13: core::option::Option<alloc::boxed::Box<FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>>::expect<alloc::boxed::Box<FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\option.rs:347
  14: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:235
  15: std::panic::{{impl}}::call_once<(),closure-0>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  16: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:331
  17: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,()>
  18: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  19: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  20: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),(),closure-0>
             at .\src\platform_impl\windows\event_loop\runner.rs:150
  21: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:233
  22: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_new_events<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:360
  23: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::move_state_to<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:299
  24: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::main_events_cleared<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:225
  25: winit::platform_impl::platform::event_loop::flush_paint_messages<()>
             at .\src\platform_impl\windows\event_loop.rs:663
  26: winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<()>
             at .\src\platform_impl\windows\event_loop.rs:1938
  27: std::panic::{{impl}}::call_once<isize,closure-0>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  28: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:331
  29: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,()>
  30: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  31: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  32: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),isize,closure-0>
             at .\src\platform_impl\windows\event_loop\runner.rs:150
  33: winit::platform_impl::platform::event_loop::thread_event_target_callback<()>
             at .\src\platform_impl\windows\event_loop.rs:2120
  34: DefSubclassProc
  35: DefSubclassProc
  36: CallWindowProcW
  37: DispatchMessageW
  38: SendMessageTimeoutW
  39: KiUserCallbackDispatcher
  40: NtUserDispatchMessage
  41: DispatchMessageW
  42: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at .\src\platform_impl\windows\event_loop.rs:215
  43: winit::platform::desktop::{{impl}}::run_return<(),closure-0>
             at .\src\platform\desktop.rs:51
  44: window_run_return2::main
             at .\examples\window_run_return2.rs:37
  45: std::rt::lang_start::{{closure}}<()>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  46: std::rt::lang_start_internal::{{closure}}
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\rt.rs:52
  47: std::panicking::try::do_call
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\panicking.rs:331
  48: std::panicking::try
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\panicking.rs:274
  49: std::panic::catch_unwind
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\panic.rs:394
  50: std::rt::lang_start_internal
             at /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b\/src\libstd\rt.rs:51
  51: std::rt::lang_start<()>
             at C:\Users\hato2\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  52: main
  53: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  54: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  55: BaseThreadInitThunk
  56: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\window_run_return2.exe` (exit code: 101)
```

just note: I got the same error when I trying to run event loop on VST environment.

**Comment by hatoo** [comment]
```rust
// Limit this example to only compatible platforms.
#[cfg(any(
    target_os = "windows",
    target_os = "macos",
    target_os = "linux",
    target_os = "dragonfly",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd"
))]
fn main() {
    use winit::{
        event::{Event, WindowEvent},
        event_loop::{ControlFlow, EventLoop},
        platform::desktop::EventLoopExtDesktop,
        window::WindowBuilder,
    };

    let mut event_loop1 = EventLoop::new();
    let mut event_loop2 = EventLoop::new();

    let window1 = WindowBuilder::new()
        .with_title("A fantastic window!")
        .build(&event_loop1)
        .unwrap();

    let window2 = WindowBuilder::new()
        .with_title("A fantastic window!")
        .build(&event_loop2)
        .unwrap();

    let mut close = false;
    while !close {
        event_loop1.run_return(|event, _, control_flow| match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => {
                close = true;
                *control_flow = ControlFlow::Exit;
            }
            _ => *control_flow = ControlFlow::Exit,
        });
        event_loop2.run_return(|event, _, control_flow| match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => {
                close = true;
                *control_flow = ControlFlow::Exit;
            }
            _ => *control_flow = ControlFlow::Exit,
        });
    }
}

#[cfg(any(target_os = "ios", target_os = "android", target_os = "emscripten"))]
fn main() {
    println!("This platform doesn't support run_return.");
}
```

I tested same kind of code and I've found it works on until `v0.21.0` but panics on `v0.22.0`.

**Comment by ryanisaacg** [comment]
Multiple event loops is not the way to go about this; you want 1 event loop, and you can create many windows from it.

**Comment by hatoo** [comment]
When we create [VST](https://github.com/RustAudio/vst-rs) plugin using winit, there is a situation that the parent window is created and handled by another application and we need to create its child window using winit. So we can't ensure that there is only one eventloop in the whole application.

Still, I need more investigation, but I'm thinking that this issue is related to why VST on winit fails. And that's why this issue is important to me.

**Comment by denis-golubev** [comment]
I ran into this issue (or a similar one), when trying to work with XAML islands (integrating UWP UI elements into classic Win32 applications). After creating an instance of `Windows.UI.Xaml.Hosting.WindowsXamlManager` / `windows::ui::xaml::hosting::WindowsXamlManager` between the initialization code and the event loop, `winit` panics with the same message.

Downgrading to version `0.21.0` fixed it for me, too.

The sample written in C++/WinRT I am trying to reimplement using Rust/WinRT can be found at [https://github.com/microsoft/Xaml-Islands-Samples/blob/master/Standalone_Samples/CppWinRT_Basic_Win32App/Win32DesktopApp/HelloWindowsDesktop.cpp](https://github.com/microsoft/Xaml-Islands-Samples/blob/master/Standalone_Samples/CppWinRT_Basic_Win32App/Win32DesktopApp/HelloWindowsDesktop.cpp). I am using [https://github.com/microsoft/winrt-rs ](https://github.com/microsoft/winrt-rs) to work with the WinRT-API.
