### ISSUE TITLE
[Windows] Crashes on assertion failed: flush_paint_messages(None, &subclass_input.event_loop_runner)

### ISSUE THREAD

**Issue by yanchith** [rust-windowing/winit#1611]
winit: 0.22.2

This happens when a windows system file dialog is opened and closed. Possibly windows sends more VM_PAINT messages while the dialog is open?

Can be reproduced on commit 597e0d2950d7d651ce64ce0194560c0f70e6cd15 in https://github.com/subdgtl/HURBAN-Selector
To reproduce, run the application, click "open" (in the panel on the left), and close the dialog that shows up.

The issue was introduced in this commit https://github.com/rust-windowing/winit/commit/b4c6cdf9a33530a2116f37a21547341c34537be1

Let me know if you need help or more information, or if I should attempt to fix it myself.

Full stack trace:

```
thread 'main' panicked at 'assertion failed: flush_paint_messages(None, &subclass_input.event_loop_runner)', C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1938:17
stack backtrace:
   0:     0x7ff76534b61f - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1:     0x7ff76534b61f - std::sys_common::backtrace::_print_fmt
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:78
   2:     0x7ff76534b61f - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff765361f7b - core::fmt::write
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\fmt\mod.rs:1063
   4:     0x7ff765347d1c - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\io\mod.rs:1426
   5:     0x7ff76534e96c - std::sys_common::backtrace::_print
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:62
   6:     0x7ff76534e96c - std::sys_common::backtrace::print
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:49
   7:     0x7ff76534e96c - std::panicking::default_hook::{{closure}}
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:204
   8:     0x7ff76534e5bf - std::panicking::default_hook
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:224
   9:     0x7ff76534f147 - std::panicking::rust_panic_with_hook
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:470
  10:     0x7ff76506a979 - std::panicking::begin_panic<str*>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:397
  11:     0x7ff765022cea - winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1938
  12:     0x7ff76500f803 - std::panic::{{impl}}::call_once<isize,closure-0>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  13:     0x7ff765003dbe - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  14:     0x7ff7653525d2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  15:     0x7ff765003916 - std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  16:     0x7ff76501041e - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  17:     0x7ff764ffdeb3 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),isize,closure-0>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  18:     0x7ff765022aef - winit::platform_impl::platform::event_loop::thread_event_target_callback<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:2120
  19:     0x7ff91632b762 - DefSubclassProc
  20:     0x7ff91632b625 - DefSubclassProc
  21:     0x7ff937495c0d - CallWindowProcW
  22:     0x7ff9374957dc - DispatchMessageW
  23:     0x7ff9374a1f73 - IsWindowVisible
  24:     0x7ff937cdfde4 - KiUserCallbackDispatcher
  25:     0x7ff934dc1764 - NtUserDispatchMessage
  26:     0x7ff9374956ec - DispatchMessageW
  27:     0x7ff9374ac08b - DialogBoxIndirectParamAorW
  28:     0x7ff9374abcff - DialogBoxIndirectParamAorW
  29:     0x7ff9374abbc2 - DialogBoxIndirectParamAorW
  30:     0x7ff9374abb58 - DialogBoxIndirectParamW
  31:     0x7ff93687ca5d - DllCanUnloadNow
  32:     0x7ff93686588a - GetFileTitleW
  33:     0x7ff9368c0fbc - PrintDlgA
  34:     0x7ff9368bfb94 - PrintDlgA
  35:     0x7ff9368b7596 - PrintDlgA
  36:     0x7ff9368997a3 - Ssync_ANSI_UNICODE_Struct_For_WOW
  37:     0x7ff936899f50 - GetOpenFileNameW
  38:     0x7ff76536c286 - tinyfd_openFileDialogW
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\libtinyfiledialogs\tinyfiledialogs.c:1680
  39:     0x7ff76536e1e0 - openFileDialogWinGui8
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\libtinyfiledialogs\tinyfiledialogs.c:1755
  40:     0x7ff76536aa95 - tinyfd_openFileDialog
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\libtinyfiledialogs\tinyfiledialogs.c:3085
  41:     0x7ff7647fd3cc - tinyfiledialogs::open_file_dialog_impl
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\src\lib.rs:199
  42:     0x7ff7647fd8d6 - tinyfiledialogs::open_file_dialog
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\src\lib.rs:225
  43:     0x7ff7645a8a47 - hurban_selector::ui::{{impl}}::draw_menu_window::{{closure}}
                               at C:\Users\yanchith\workspace\subdgtl\HURBAN-Selector\src\ui.rs:1046
  44:     0x7ff7646a9d09 - imgui::window::Window::build<closure-0>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\imgui-0.3.0\src\window\mod.rs:539
  45:     0x7ff76450a823 - hurban_selector::ui::UiFrame::draw_menu_window
                               at C:\Users\yanchith\workspace\subdgtl\HURBAN-Selector\src\ui.rs:830
  46:     0x7ff7646e8930 - hurban_selector::init_and_run::{{closure}}
                               at C:\Users\yanchith\workspace\subdgtl\HURBAN-Selector\src\lib.rs:465
  47:     0x7ff76465e3f8 - winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:200
  48:     0x7ff765013a63 - alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc\boxed.rs:1024
  49:     0x7ff764ffeebb - winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:239
  50:     0x7ff76500f7c6 - std::panic::{{impl}}::call_once<(),closure-0>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  51:     0x7ff765003d50 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  52:     0x7ff7653525d2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  53:     0x7ff765003ac6 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  54:     0x7ff765010386 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  55:     0x7ff764ffe309 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),(),closure-0>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  56:     0x7ff764ffec51 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:233
  57:     0x7ff764fff537 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::move_state_to<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:319
  58:     0x7ff764ffebd7 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::main_events_cleared<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:225
  59:     0x7ff765022775 - winit::platform_impl::platform::event_loop::flush_paint_messages<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:663
  60:     0x7ff765022c78 - winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1938
  61:     0x7ff76500f803 - std::panic::{{impl}}::call_once<isize,closure-0>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  62:     0x7ff765003dbe - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  63:     0x7ff7653525d2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  64:     0x7ff765003916 - std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  65:     0x7ff76501041e - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  66:     0x7ff764ffdeb3 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),isize,closure-0>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  67:     0x7ff765022aef - winit::platform_impl::platform::event_loop::thread_event_target_callback<()>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:2120
  68:     0x7ff91632b762 - DefSubclassProc
  69:     0x7ff91632b625 - DefSubclassProc
  70:     0x7ff937495c0d - CallWindowProcW
  71:     0x7ff9374957dc - DispatchMessageW
  72:     0x7ff9374a1f73 - IsWindowVisible
  73:     0x7ff937cdfde4 - KiUserCallbackDispatcher
  74:     0x7ff934dc1764 - NtUserDispatchMessage
  75:     0x7ff9374956ec - DispatchMessageW
  76:     0x7ff76465e0c6 - winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:215
  77:     0x7ff76465e476 - winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:185
  78:     0x7ff7645057ad - winit::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\yanchith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\event_loop.rs:149
  79:     0x7ff7644f3441 - hurban_selector::init_and_run
                               at C:\Users\yanchith\workspace\subdgtl\HURBAN-Selector\src\lib.rs:260
  80:     0x7ff7644f1d6b - hurban_selector::main
                               at C:\Users\yanchith\workspace\subdgtl\HURBAN-Selector\src\main.rs:72
  81:     0x7ff7644f1a1b - std::rt::lang_start::{{closure}}<()>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\rt.rs:67
  82:     0x7ff76534eb67 - std::rt::lang_start_internal::{{closure}}
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\rt.rs:52
  83:     0x7ff76534eb67 - std::panicking::try::do_call<closure-0,i32>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:303
  84:     0x7ff7653525d2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  85:     0x7ff76534f498 - std::panicking::try
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:281
  86:     0x7ff76534f498 - std::panic::catch_unwind
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panic.rs:394
  87:     0x7ff76534f498 - std::rt::lang_start_internal
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\rt.rs:51
  88:     0x7ff7644f19f3 - std::rt::lang_start<()>
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\rt.rs:67
  89:     0x7ff7644f1d90 - main
  90:     0x7ff765609d30 - invoke_main
                               at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  91:     0x7ff765609d30 - __scrt_common_main_seh
                               at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  92:     0x7ff937637bd4 - BaseThreadInitThunk
  93:     0x7ff937cace51 - RtlUserThreadStart
```

**Comment by Osspial** [comment]
Could you check to see if #1615 fixes this?

**Comment by yanchith** [comment]
Yes, it does! Thank you :)
