### ISSUE TITLE
Panic when turn `control_flow` into ControlFlow::Exit

### ISSUE THREAD

**Issue by SergeevPavel** [rust-windowing/winit#1693]
I got this exception on MacOS when all windows was already disposed and I set `control_flow` into `ControlFlow::Exit`.
```
thread '<unnamed>' panicked at 'Uncaught exception <NSException: 0x7fac1aa672a0>', /Users/pavel/.cargo/git/checkouts/winit-d99232a607dbf5c5/58209cb/src/platform_impl/macos/app_state.rs:344:34
    0: backtrace::capture::Backtrace::create
   1: backtrace::capture::Backtrace::new
   2: photon::photon_api::panic_hook
   3: std::panicking::rust_panic_with_hook
   4: _rust_begin_unwind
   5: std::panicking::begin_panic_fmt
   6: winit::platform_impl::platform::app_state::AppState::cleared
   7: ___CFRunLoopRun
   8: ___CFRunLoopRun
   9: _CFRunLoopRunSpecific
  10: _____kCFPasteboardFilenamesFlavor_block_invoke
  11: _RunCurrentEventLoopInMode
  12: _ReceiveNextEventCommon
  13: __BlockUntilNextEventMatchingListInModeWithFilter
  14: __DPSNextEvent
  15: -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
  16: -[NSApplication run]
  17: objc_exception::try_no_ret::try_objc_execute_closure
  18: _RustObjCExceptionTryCatch
  19: objc::message::platform::send_unverified
  20: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
```
It's seems strange for me because application without windows could be still accessible on Mac e.g. from app menu.

Also if you will set `ControlFlow::Exit` before first window will be created you will see:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/platform_impl/macos/app_state.rs:272:21
stack backtrace:

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by Hankszhang** [comment]
I also run into this issue, is there a way to exit the Eventloop without a window?

**Comment by francesca64** [comment]
Sorry for the delay! This seems like a bug in winit. @SergeevPavel it looks like you took a stab at solving this, but never made a PR for it?

**Comment by lachlansneff** [comment]
I'm running into this bug as well. Would a pr that fixes this be merged?

**Comment by francesca64** [comment]
@lachlansneff absolutely! A PR to fix this would be greatly appreciated.

**Comment by madsmtm** [comment]
I think this was posted in #1869 as well, which was fixed by #1874 - can someone confirm this?

**Comment by madsmtm** [comment]
I'll assume that this issue was fixed by #1874
