### ISSUE TITLE
Panic due to an uninitialized value on Rust 1.48

### ISSUE THREAD

**Issue by vilunov** [rust-windowing/winit#1778]
First encountered by me in https://github.com/amethyst/amethyst/issues/2524, but also reproduced with [barnes-hut-rs](https://github.com/Katsutoshii/barnes-hut-rs), which does not use amethyst.

The panic is raised when a mouse cursor is moved over the window.

Stack trace:
```
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/nikita/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::mem::uninitialized
             at /home/nikita/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658
   4: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/util/input.rs:94
   5: winit::platform::platform::x11::EventsLoop::process_event
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:956
   6: winit::platform::platform::x11::EventsLoop::poll_events
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:270
   7: winit::platform::platform::EventsLoop::poll_events
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/mod.rs:522
   8: winit::EventsLoop::poll_events
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/lib.rs:277
   9: glutin_window::GlutinWindow::poll_event
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.66.0/src/lib.rs:204
  10: <glutin_window::GlutinWindow as window::Window>::poll_event
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.66.0/src/lib.rs:449
  11: event_loop::Events::next
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-event_loop-0.52.0/src/lib.rs:346
  12: barnes_hut::main
             at ./src/main.rs:143
  13: core::ops::function::FnOnce::call_once
             at /home/nikita/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
```

**Comment by kchibisov** [comment]
The current winit version is 0.23.0, older winit isn't supported.
