### ISSUE TITLE
Examples panic when Nvidia driver is enabled

### ISSUE THREAD

**Issue by rikvdkleij** [rust-windowing/winit#1801]
On Ubuntu 20.10 the examples panics with error:
```
thread 'main' panicked at 'Instance creation error: VkError(ERROR_LAYER_NOT_PRESENT)', examples/src/lib.rs:237:18
```

Backtrace:
<details>
```
🔋100% ✗ RUST_BACKTRACE=full cargo run --bin triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `/home/rik/graphics/ash/target/debug/triangle`
thread 'main' panicked at 'Instance creation error: VkError(ERROR_LAYER_NOT_PRESENT)', examples/src/lib.rs:237:18
stack backtrace:
   0:     0x563708687bd0 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x563708687bd0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x563708687bd0 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x563708687bd0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x5637086a812c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x563708684b92 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x563708689f5d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x563708689f5d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x563708689f5d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x563708689c08 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x56370868a641 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x56370868a1e9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x56370868803c - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x56370868a1a9 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x5637086a6a01 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x5637086a6823 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x56370836f030 - core::result::Result<T,E>::expect::he0952449e7c9e040
                               at /home/rik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933
  17:     0x5637083714ef - examples::ExampleBase::new::h1c81b39b07150899
                               at /home/rik/graphics/ash/examples/src/lib.rs:235
  18:     0x563708364835 - triangle::main::he0555801ca357519
                               at /home/rik/graphics/ash/examples/src/bin/triangle.rs:18
  19:     0x563708367c5b - core::ops::function::FnOnce::call_once::h4e175047d62338fd
                               at /home/rik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  20:     0x56370836473e - std::sys_common::backtrace::__rust_begin_short_backtrace::h37bf97adc06a26dd
                               at /home/rik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  21:     0x563708352631 - std::rt::lang_start::{{closure}}::h05da0d84ff6009df
                               at /home/rik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  22:     0x56370868aa67 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  23:     0x56370868aa67 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  24:     0x56370868aa67 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  25:     0x56370868aa67 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  26:     0x56370868aa67 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  27:     0x563708352607 - std::rt::lang_start::hb0217ad538c3dd9c
                               at /home/rik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  28:     0x56370836721a - main
  29:     0x7fb018161cb2 - __libc_start_main
  30:     0x5637083490ce - _start
  31:                0x0 - <unknown>
```

</details>

nvidia-smi:
<details>

```
Tue Dec 15 09:18:43 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   57C    P0    28W /  N/A |    609MiB /  6078MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1811      G   /usr/lib/xorg/Xorg                367MiB |
|    0   N/A  N/A      1997      G   /usr/bin/gnome-shell              103MiB |
|    0   N/A  N/A      2278      G   ...AAAAAAAAA= --shared-files        2MiB |
|    0   N/A  N/A     15782      G   ...AAAAAAAA== --shared-files      131MiB |
+-----------------------------------------------------------------------------+
```
</details>

`vkcube` works.

**Comment by kchibisov** [comment]
well, the error is from vulkan, winit has nothing to do with vulkan, so bring it to ash so they can understand why it's happening? Winit just creates an X11 window and a pointer to a window.

**Comment by rikvdkleij** [comment]
@kchibisov 

Yeah, sorry, was by accident.

**Comment by maroider** [comment]
There is admittedly an interesting panic that was encountered in gfx-rs/wgpu-rs#673, where Winit panics on [this line](https://github.com/rust-windowing/winit/blob/v0.23.0/src/platform_impl/linux/x11/event_processor.rs#L884), but that's not what's reported here.

**Comment by rikvdkleij** [comment]
@maroider 

Yes, that's reported here https://github.com/rust-windowing/winit/issues/1800

**Comment by maroider** [comment]
Ah, my bad. The issue title had me confused.
