### ISSUE TITLE
Can't open a window on Wayland.

### ISSUE THREAD

**Issue by NoraCodes** [rust-windowing/winit#1913]
I'm working on an application using `ggez`, which uses `winit` as its underlying windowing platform. When I attempt to run even the example `ggez` application, I get an error output like this (with RUST_BACKTRACE and WAYLAND_DEBUG set):

```
[1209832.957]  -> wl_display@1.get_registry(new id wl_registry@2)
[1209832.978]  -> wl_display@1.sync(new id wl_callback@3)
[1209833.080] wl_display@1.delete_id(3)
[1209833.106] wl_registry@2.global(1, "wl_drm", 2)
[1209833.156] wl_registry@2.global(2, "wl_compositor", 4)
[1209833.171] wl_registry@2.global(3, "wl_shm", 1)
[1209833.182] wl_registry@2.global(5, "zxdg_output_manager_v1", 3)
[1209833.192] wl_registry@2.global(6, "wl_data_device_manager", 3)
[1209833.205] wl_registry@2.global(7, "zwp_primary_selection_device_manager_v1", 1)
[1209833.217] wl_registry@2.global(8, "gtk_primary_selection_device_manager", 1)
[1209833.227] wl_registry@2.global(9, "wl_subcompositor", 1)
[1209833.237] wl_registry@2.global(10, "xdg_wm_base", 3)
[1209833.249] wl_registry@2.global(11, "zxdg_shell_v6", 1)
[1209833.264] wl_registry@2.global(12, "wl_shell", 1)
[1209833.274] wl_registry@2.global(13, "gtk_shell1", 3)
[1209833.284] wl_registry@2.global(14, "wp_viewporter", 1)
[1209833.294] wl_registry@2.global(15, "zwp_pointer_gestures_v1", 1)
[1209833.304] wl_registry@2.global(16, "zwp_tablet_manager_v2", 1)
[1209833.314] wl_registry@2.global(17, "wl_seat", 5)
[1209833.369]  -> wl_registry@2.bind(17, "wl_seat", 5, new id [unknown]@4)
[1209833.415] wl_registry@2.global(18, "zwp_relative_pointer_manager_v1", 1)
[1209833.433] wl_registry@2.global(19, "zwp_pointer_constraints_v1", 1)
[1209833.443] wl_registry@2.global(20, "zxdg_exporter_v1", 1)
[1209833.453] wl_registry@2.global(21, "zxdg_importer_v1", 1)
[1209833.463] wl_registry@2.global(22, "zwp_linux_dmabuf_v1", 3)
[1209833.473] wl_registry@2.global(23, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[1209833.483] wl_registry@2.global(24, "zwp_text_input_manager_v3", 1)
[1209833.493] wl_registry@2.global(25, "gtk_text_input_manager", 1)
[1209833.503] wl_registry@2.global(32, "wl_output", 2)
[1209833.525]  -> wl_registry@2.bind(32, "wl_output", 2, new id [unknown]@5)
[1209833.557] wl_callback@3.done(11469)
[1209833.566]  -> wl_display@1.sync(new id wl_callback@3)
[1209833.637] wl_display@1.delete_id(3)
[1209833.645] wl_seat@4.capabilities(3)
[1209833.662]  -> wl_seat@4.get_pointer(new id wl_pointer@6)
[1209842.263]  -> wl_seat@4.get_keyboard(new id wl_keyboard@7)
[1209842.290] wl_seat@4.name("seat0")
[1209842.304] wl_output@5.geometry(0, 0, 530, 290, 0, "ELE", "E1SW2418M", 0)
[1209842.345] wl_output@5.mode(3, 1920, 1080, 60000)
[1209842.358] wl_output@5.scale(1)
[1209842.364] wl_output@5.done()
[1209842.384] wl_callback@3.done(11469)
[1209842.430]  -> wl_registry@2.bind(2, "wl_compositor", 4, new id [unknown]@3)
[1209842.460]  -> wl_registry@2.bind(9, "wl_subcompositor", 1, new id [unknown]@8)
[1209842.485]  -> wl_registry@2.bind(3, "wl_shm", 1, new id [unknown]@9)
[1209842.507]  -> wl_registry@2.bind(6, "wl_data_device_manager", 3, new id [unknown]@10)
[1209842.530]  -> wl_registry@2.bind(10, "xdg_wm_base", 3, new id [unknown]@11)
[1209842.553]  -> wl_display@1.sync(new id wl_callback@12)
[1209843.258] wl_display@1.delete_id(12)
[1209843.266] wl_keyboard@7.keymap(1, fd 4, 50916)
[1209844.956] wl_keyboard@7.repeat_info(33, 500)
[1209844.966] wl_shm@9.format(0)
[1209844.976] wl_shm@9.format(1)
[1209844.982] wl_callback@12.done(11469)
[1209845.092]  -> wl_compositor@3.create_surface(new id wl_surface@12)
[1209845.114]  -> wl_compositor@3.create_surface(new id wl_surface@13)
[1209845.125]  -> wl_subcompositor@8.get_subsurface(new id wl_subsurface@14, wl_surface@13, wl_surface@12)
[1209845.132]  -> wl_compositor@3.create_surface(new id wl_surface@15)
[1209845.137]  -> wl_subcompositor@8.get_subsurface(new id wl_subsurface@16, wl_surface@15, wl_surface@12)
[1209845.143]  -> wl_compositor@3.create_surface(new id wl_surface@17)
[1209845.148]  -> wl_subcompositor@8.get_subsurface(new id wl_subsurface@18, wl_surface@17, wl_surface@12)
[1209845.154]  -> wl_compositor@3.create_surface(new id wl_surface@19)
[1209845.158]  -> wl_subcompositor@8.get_subsurface(new id wl_subsurface@20, wl_surface@19, wl_surface@12)
[1209845.164]  -> wl_compositor@3.create_surface(new id wl_surface@21)
[1209845.169]  -> wl_subcompositor@8.get_subsurface(new id wl_subsurface@22, wl_surface@21, wl_surface@12)
[1209845.190]  -> wl_shm@9.create_pool(new id wl_shm_pool@23, fd 5, 128)
[1209845.211]  -> wl_shm@9.create_pool(new id wl_shm_pool@24, fd 7, 128)
[1209845.357]  -> wl_shm@9.create_pool(new id wl_shm_pool@25, fd 9, 1024)
[1209845.463]  -> wl_shm_pool@25.resize(6144)
[1209845.500]  -> wl_shm_pool@25.resize(16384)
[1209845.954]  -> wl_shm_pool@25.resize(36864)
[1209845.981]  -> wl_shm_pool@25.resize(77824)
[1209846.013]  -> wl_shm_pool@25.resize(159744)
[1209846.352]  -> wl_shm_pool@25.resize(323584)
[1209847.237]  -> wl_shm_pool@25.resize(651264)
[1209849.238]  -> wl_shm_pool@25.resize(1306624)
[1209857.012]  -> xdg_wm_base@11.get_xdg_surface(new id xdg_surface@26, wl_surface@12)
[1209857.050]  -> xdg_surface@26.get_toplevel(new id xdg_toplevel@27)
[1209857.059]  -> wl_surface@12.commit()
[1209857.070]  -> xdg_toplevel@27.set_min_size(2, 31)
[1209857.076]  -> xdg_surface@26.set_window_geometry(0, -30, 800, 630)
[1209857.092]  -> xdg_toplevel@27.set_title("An easy, good game")
[1209857.110]  -> wl_compositor@3.create_surface(new id wl_surface@28)
[1209857.130]  -> wl_seat@4.get_pointer(new id wl_pointer@29)
[1209857.153]  -> xdg_toplevel@27.set_min_size(800, 630)
[1209857.158]  -> xdg_toplevel@27.set_max_size(800, 630)
[1209857.163]  -> xdg_toplevel@27.set_min_size(2, 31)
[1209857.167]  -> xdg_toplevel@27.set_max_size(0, 0)
[1209857.188]  -> wl_display@1.sync(new id wl_callback@30)
[1209861.020] wl_display@1.delete_id(30)
[1209861.034] xdg_toplevel@27.configure(0, 0, array)
[1209861.091] xdg_surface@26.configure(79)
[1209861.102]  -> xdg_surface@26.ack_configure(79)
[1209861.107] wl_callback@30.done(11469)
[1209862.491]  -> wl_display@1.get_registry(new id wl_registry@30)
[1209862.503]  -> wl_display@1.sync(new id wl_callback@31)
[1209865.588] wl_display@1.delete_id(31)
[1209865.601] wl_registry@30.global(1, "wl_drm", 2)
[1209865.612]  -> wl_registry@30.bind(1, "wl_drm", 2, new id [unknown]@32)
[1209865.620] wl_registry@30.global(2, "wl_compositor", 4)
[1209865.625] wl_registry@30.global(3, "wl_shm", 1)
[1209865.629] wl_registry@30.global(5, "zxdg_output_manager_v1", 3)
[1209865.634] wl_registry@30.global(6, "wl_data_device_manager", 3)
[1209865.638] wl_registry@30.global(7, "zwp_primary_selection_device_manager_v1", 1)
[1209865.643] wl_registry@30.global(8, "gtk_primary_selection_device_manager", 1)
[1209865.648] wl_registry@30.global(9, "wl_subcompositor", 1)
[1209865.652] wl_registry@30.global(10, "xdg_wm_base", 3)
[1209865.657] wl_registry@30.global(11, "zxdg_shell_v6", 1)
[1209865.661] wl_registry@30.global(12, "wl_shell", 1)
[1209865.666] wl_registry@30.global(13, "gtk_shell1", 3)
[1209865.670] wl_registry@30.global(14, "wp_viewporter", 1)
[1209865.675] wl_registry@30.global(15, "zwp_pointer_gestures_v1", 1)
[1209865.680] wl_registry@30.global(16, "zwp_tablet_manager_v2", 1)
[1209865.684] wl_registry@30.global(17, "wl_seat", 5)
[1209865.689] wl_registry@30.global(18, "zwp_relative_pointer_manager_v1", 1)
[1209865.693] wl_registry@30.global(19, "zwp_pointer_constraints_v1", 1)
[1209865.697] wl_registry@30.global(20, "zxdg_exporter_v1", 1)
[1209865.702] wl_registry@30.global(21, "zxdg_importer_v1", 1)
[1209865.706] wl_registry@30.global(22, "zwp_linux_dmabuf_v1", 3)
[1209865.711]  -> wl_registry@30.bind(22, "zwp_linux_dmabuf_v1", 3, new id [unknown]@33)
[1209865.717] wl_registry@30.global(23, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[1209865.722] wl_registry@30.global(24, "zwp_text_input_manager_v3", 1)
[1209865.726] wl_registry@30.global(25, "gtk_text_input_manager", 1)
[1209865.731] wl_registry@30.global(32, "wl_output", 2)
[1209865.736] wl_callback@31.done(11469)
[1209865.739]  -> wl_display@1.sync(new id wl_callback@31)
[1209865.894] wl_display@1.delete_id(31)
[1209865.899] wl_drm@32.device("/dev/dri/card0")
[1209866.006]  -> wl_drm@32.authenticate(1)
[1209866.013] wl_drm@32.format(808669761)
[1209866.017] wl_drm@32.format(808669784)
[1209866.019] wl_drm@32.format(808665665)
[1209866.022] wl_drm@32.format(808665688)
[1209866.025] wl_drm@32.format(875713089)
[1209866.027] wl_drm@32.format(875713112)
[1209866.030] wl_drm@32.format(909199186)
[1209866.032] wl_drm@32.format(961959257)
[1209866.035] wl_drm@32.format(825316697)
[1209866.037] wl_drm@32.format(842093913)
[1209866.040] wl_drm@32.format(909202777)
[1209866.042] wl_drm@32.format(875713881)
[1209866.045] wl_drm@32.format(842094158)
[1209866.048] wl_drm@32.format(909203022)
[1209866.050] wl_drm@32.format(1448695129)
[1209866.053] wl_drm@32.capabilities(1)
[1209866.055] zwp_linux_dmabuf_v1@33.format(875713089)
[1209866.058] zwp_linux_dmabuf_v1@33.modifier(875713089, 16777215, 4294967295)
[1209866.063] zwp_linux_dmabuf_v1@33.format(875713112)
[1209866.066] zwp_linux_dmabuf_v1@33.modifier(875713112, 16777215, 4294967295)
[1209866.071] zwp_linux_dmabuf_v1@33.format(808669761)
[1209866.074] zwp_linux_dmabuf_v1@33.modifier(808669761, 16777215, 4294967295)
[1209866.078] zwp_linux_dmabuf_v1@33.format(909199186)
[1209866.081] zwp_linux_dmabuf_v1@33.modifier(909199186, 16777215, 4294967295)
[1209866.086] wl_callback@31.done(11469)
[1209866.089]  -> wl_display@1.sync(new id wl_callback@31)
[1209866.136] wl_display@1.delete_id(31)
[1209866.141] wl_drm@32.authenticated()
[1209866.143] wl_callback@31.done(11469)
[1209905.316]  -> xdg_toplevel@27.unset_maximized()
[1209905.337]  -> xdg_toplevel@27.set_min_size(2, 31)
[1209905.343]  -> xdg_toplevel@27.set_max_size(0, 0)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/nora/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/wayland/window.rs:290:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /home/nora/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: winit::platform::platform::wayland::window::Window::get_current_monitor
             at /home/nora/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/wayland/window.rs:290:22
   5: winit::platform::platform::Window::get_current_monitor
             at /home/nora/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/mod.rs:358:87
   6: winit::window::<impl winit::Window>::get_current_monitor
             at /home/nora/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/window.rs:412:9
   7: ggez::graphics::context::GraphicsContextGeneric<B>::set_window_mode
             at /home/nora/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/graphics/context.rs:537:23
   8: ggez::graphics::context::GraphicsContextGeneric<ggez::graphics::GlBackendSpec>::new
             at /home/nora/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/graphics/context.rs:301:9
   9: ggez::context::Context::from_conf
             at /home/nora/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/context.rs:88:32
  10: ggez::context::ContextBuilder::build
             at /home/nora/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/context.rs:304:9
  11: sunnytracker::main
             at ./src/main.rs:235:37
  12: core::ops::function::FnOnce::call_once
             at /home/nora/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1209937.587]  -> zwp_linux_dmabuf_v1@33.destroy()
[1209937.656]  -> wl_pointer@29.release()
[1209937.666]  -> wl_shm_pool@23.destroy()
[1209937.680]  -> wl_shm_pool@24.destroy()
[1209937.697]  -> xdg_toplevel@27.destroy()
[1209937.702]  -> xdg_surface@26.destroy()
```
I've tried looking at other issues but I don't see any other mentions of this problem.

**Comment by maroider** [comment]
Please use the latest version of Winit (you seem to be using `0.19.5`, through `ggez` `0.5.1`).
Older versions of Winit are not supported.

`ggez` `0.6.0-rc1` should be using Winit `0.24.0`, which is the newest version.

**Comment by maroider** [comment]
I'm going to close this for now. Feel free to re-open the issue if you still have the same problem with the latest version of Winit.
