### ISSUE TITLE
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid'

### ISSUE THREAD

**Issue by uzytkownik** [rust-windowing/winit#1943]
When I try to run amethyst example the app crashes:

```
(gdb) bt
#0  std::panicking::rust_panic () at library/std/src/panicking.rs:640
#1  0x0000555556578784 in std::panicking::rust_panic_with_hook () at library/std/src/panicking.rs:610
#2  0x0000555556578297 in std::panicking::begin_panic_handler::{{closure}} () at library/std/src/panicking.rs:495
#3  0x00005555565764cc in std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!> () at library/std/src/sys_common/backtrace.rs:141
#4  0x0000555556578229 in std::panicking::begin_panic_handler () at library/std/src/panicking.rs:493
#5  0x00005555556a97b1 in core::panicking::panic_fmt () at library/core/src/panicking.rs:92
#6  0x00005555556a96fd in core::panicking::panic () at library/core/src/panicking.rs:50
#7  0x0000555555ec4c20 in core::mem::uninitialized<winit::platform::platform::x11::util::input::PointerState> ()
    at (...)/mpiechotka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:660
#8  winit::platform::platform::x11::xdisplay::XConnection::query_pointer (self=0x555556aaacd0, window=52428802, device_id=2)
    at (...)/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/util/input.rs:94
#9  0x0000555555c9e87f in winit::platform::platform::x11::EventsLoop::process_event<&mut closure-0> (self=0x555556a981d8, xev=0x7fffffff3d10, callback=0x7fffffff3d08)
    at (...)/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:956
#10 0x0000555555c9886d in winit::platform::platform::x11::EventsLoop::poll_events<closure-0> (self=0x555556a981d8, callback=...)
    at (...)/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:270
#11 0x0000555555c88949 in winit::platform::platform::EventsLoop::poll_events<closure-0> (self=0x555556a981d0, callback=...)
    at (...)/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/mod.rs:522
#12 0x0000555555c7f9e4 in winit::EventsLoop::poll_events<closure-0> (self=0x555556a981d0, callback=...)
    at (...)/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/lib.rs:277
#13 0x0000555555ca6c4a in amethyst_window::system::{{impl}}::run_now (self=0x555556a981d0, world=0x7fffffff5818)
    at (...)/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_window-0.15.3/src/system.rs:116
```

**Comment by msiglreith** [comment]
Hello, thanks for reporting. It's discussed in #1773 and #1778
Resolution was that 0.19 won't be patched and latest winit version should be used
