### ISSUE TITLE
winit 0.26.1: assertion failed: validate_scale_factor(scale_factor)

### ISSUE THREAD

**Issue by ngirard** [rust-windowing/winit#2161]
Heya,
I'm running X11 on Kubuntu 21.10.
While trying [Bevy](https://github.com/bevyengine/bevy/issues/3753), which depends on Winit 0.26.1, I got the following problem:

```
     Running `/home/ngirard/sandboxes/rust/./target/debug/examples/breakout`
2022-01-23T20:17:11.323894Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 0    
thread 'main' panicked at 'assertion failed: validate_scale_factor(scale_factor)', /home/ngirard/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/dpi.rs:351:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After modifying [this debugging message](https://github.com/rust-windowing/winit/blob/9229e2d88b7be23bc4416179afcfd9fdc82b9a52/src/platform_impl/linux/x11/window.rs#L142) from
```rs
info!("Guessed window scale factor: {}", scale_factor);
```
to
```rs
info!("Guessed window scale factor: {}; guessed_monitor: {:#?}", scale_factor, guessed_monitor);
```
and recompiling, I'm getting
```
2022-01-23T21:03:12.904029Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 0; guessed_monitor: MonitorHandle {
    id: 65,
    name: "HDMI-1",
    dimensions: (
        1920,
        1080,
    ),
    position: (
        0,
        0,
    ),
    primary: true,
    scale_factor: 0.0,
    rect: AaRect {
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
    },
    video_modes: [
        VideoMode {
            size: (
                1024,
                768,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 83,
            monitor: None,
        },
        VideoMode {
            size: (
                800,
                600,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 98,
            monitor: None,
        },
        VideoMode {
            size: (
                640,
                480,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 113,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                1024,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 141,
            monitor: None,
        },
        VideoMode {
            size: (
                1920,
                1080,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 148,
            monitor: None,
        },
        VideoMode {
            size: (
                1920,
                1080,
            ),
            bit_depth: 24,
            refresh_rate: 50,
            native_mode: 149,
            monitor: None,
        },
        VideoMode {
            size: (
                1920,
                1080,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 150,
            monitor: None,
        },
        VideoMode {
            size: (
                1680,
                1050,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 151,
            monitor: None,
        },
        VideoMode {
            size: (
                1600,
                900,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 152,
            monitor: None,
        },
        VideoMode {
            size: (
                1440,
                900,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 153,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                800,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 154,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                720,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 155,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                720,
            ),
            bit_depth: 24,
            refresh_rate: 50,
            native_mode: 156,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                720,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 157,
            monitor: None,
        },
        VideoMode {
            size: (
                720,
                576,
            ),
            bit_depth: 24,
            refresh_rate: 50,
            native_mode: 158,
            monitor: None,
        },
        VideoMode {
            size: (
                720,
                480,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 159,
            monitor: None,
        },
        VideoMode {
            size: (
                720,
                480,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 160,
            monitor: None,
        },
        VideoMode {
            size: (
                640,
                480,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 161,
            monitor: None,
        },
    ],
}     
```

so `guessed_monitor` seems to be correct except for the scale factor.

Heres' the (partial) output of `xdpyinfo`:
```
name of display:    :0
version number:    11.0
vendor string:    The X.Org Foundation
vendor release number:    12013000
X.Org version: 1.20.13
maximum request size:  16777212 bytes
motion buffer size:  256
bitmap unit, bit order, padding:    32, LSBFirst, 32
image byte order:    LSBFirst
number of supported pixmap formats:    7
supported pixmap formats:
    depth 1, bits_per_pixel 1, scanline_pad 32
    depth 4, bits_per_pixel 8, scanline_pad 32
    depth 8, bits_per_pixel 8, scanline_pad 32
    depth 15, bits_per_pixel 16, scanline_pad 32
    depth 16, bits_per_pixel 16, scanline_pad 32
    depth 24, bits_per_pixel 32, scanline_pad 32
    depth 32, bits_per_pixel 32, scanline_pad 32
keycode range:    minimum 8, maximum 255
focus:  window 0x9600007, revert to PointerRoot
number of extensions:    28
    BIG-REQUESTS
    Composite
    DAMAGE
    DOUBLE-BUFFER
    DPMS
    DRI2
    DRI3
    GLX
    Generic Event Extension
    MIT-SCREEN-SAVER
    MIT-SHM
    Present
    RANDR
    RECORD
    RENDER
    SECURITY
    SHAPE
    SYNC
    X-Resource
    XC-MISC
    XFIXES
    XFree86-DGA
    XFree86-VidModeExtension
    XINERAMA
    XInputExtension
    XKEYBOARD
    XTEST
    XVideo
default screen number:    0
number of screens:    1

screen #0:
  dimensions:    3199x1080 pixels (844x285 millimeters)
  resolution:    96x96 dots per inch
  depths (7):    24, 1, 4, 8, 15, 16, 32
  root window id:    0x17c
  depth of root window:    24 planes
  number of colormaps:    minimum 1, maximum 1
  default colormap:    0x20
  default number of colormap cells:    256
  preallocated pixels:    black 0, white 16777215
  options:    backing-store WHEN MAPPED, save-unders NO
  largest cursor:    256x256
  current input event mask:    0xfa8033
    KeyPressMask             KeyReleaseMask           EnterWindowMask          
    LeaveWindowMask          ExposureMask             StructureNotifyMask      
    SubstructureNotifyMask   SubstructureRedirectMask FocusChangeMask          
    PropertyChangeMask       ColormapChangeMask       
  number of visuals:    90
  default visual id:  0x21
  visual:
    visual id:    0x21
    class:    TrueColor
    depth:    24 planes
    available colormap entries:    256 per subfield
    red, green, blue masks:    0xff0000, 0xff00, 0xff
    significant bits in color specification:    8 bits
    (...)
```

Any thoughts ?
Thanks !

**Comment by maroider** [comment]
What does `xrandr` say?

**Comment by ngirard** [comment]
Hi @maroider, there you are:
```
Screen 0: minimum 320 x 200, current 3199 x 1080, maximum 16384 x 16384
LVDS-1 connected (normal left inverted right x axis y axis)
   1366x768      60.02 +
   1360x768      59.80    59.96  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
VGA-1 connected 1280x1024+1919+0 (normal left inverted right x axis y axis) 376mm x 301mm
   1280x1024     60.02 +  75.02* 
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+  50.00    59.94  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.90  
   1280x800      59.91  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
HDMI-3 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
```

**Comment by ngirard** [comment]
(FWIW, disconnecting VGA-1 didn't solve the problem)

**Comment by ngirard** [comment]
<details>
<summary>
After disconnecting VGA-1:
</summary>

```
RUST_BACKTRACE=1 cargo run --features bevy/dynamic --example many_sprites
    Finished dev [unoptimized + debuginfo] target(s) in 0.66s
     Running `/home/ngirard/sandboxes/rust/./target/debug/examples/many_sprites`
2022-01-23T21:52:40.243339Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 0; guessed_monitor: MonitorHandle {
    id: 65,
    name: "HDMI-1",
    dimensions: (
        1920,
        1080,
    ),
    position: (
        0,
        0,
    ),
    primary: true,
    scale_factor: 0.0,
    rect: AaRect {
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
    },
    video_modes: [
        VideoMode {
            size: (
                1024,
                768,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 83,
            monitor: None,
        },
        VideoMode {
            size: (
                800,
                600,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 98,
            monitor: None,
        },
        VideoMode {
            size: (
                640,
                480,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 113,
            monitor: None,
        },
        VideoMode {
            size: (
                1920,
                1080,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 148,
            monitor: None,
        },
        VideoMode {
            size: (
                1920,
                1080,
            ),
            bit_depth: 24,
            refresh_rate: 50,
            native_mode: 149,
            monitor: None,
        },
        VideoMode {
            size: (
                1920,
                1080,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 150,
            monitor: None,
        },
        VideoMode {
            size: (
                1680,
                1050,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 151,
            monitor: None,
        },
        VideoMode {
            size: (
                1600,
                900,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 152,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                1024,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 141,
            monitor: None,
        },
        VideoMode {
            size: (
                1440,
                900,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 153,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                800,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 154,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                720,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 155,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                720,
            ),
            bit_depth: 24,
            refresh_rate: 50,
            native_mode: 156,
            monitor: None,
        },
        VideoMode {
            size: (
                1280,
                720,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 157,
            monitor: None,
        },
        VideoMode {
            size: (
                720,
                576,
            ),
            bit_depth: 24,
            refresh_rate: 50,
            native_mode: 158,
            monitor: None,
        },
        VideoMode {
            size: (
                720,
                480,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 159,
            monitor: None,
        },
        VideoMode {
            size: (
                720,
                480,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 160,
            monitor: None,
        },
        VideoMode {
            size: (
                640,
                480,
            ),
            bit_depth: 24,
            refresh_rate: 60,
            native_mode: 161,
            monitor: None,
        },
    ],
}    
thread 'main' panicked at 'assertion failed: validate_scale_factor(scale_factor)', /home/ngirard/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/dpi.rs:351:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: winit::dpi::LogicalSize<P>::to_physical
             at /home/ngirard/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/dpi.rs:351:9
   4: winit::dpi::Size::to_physical
             at /home/ngirard/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/dpi.rs:509:36
   5: winit::platform_impl::platform::x11::window::UnownedWindow::new::{{closure}}
             at /home/ngirard/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/x11/window.rs:149:25```

</details>

**Comment by maroider** [comment]
Welp, the measurements for `HDMI-1` seem reasonable, at least.

The scale factor seems to be calculated [here](https://github.com/rust-windowing/winit/blob/0b3902413394f658ef7349d67820db76d56e4c49/src/platform_impl/linux/x11/util/randr.rs#L132-L162). Could you try to figure out which branch is being taken there?

**Comment by ngirard** [comment]
> (I also hope you don't mind me wrapping stuff in `<details>`)

Actually I just found it dope. I stole the trick immediately ;-)

**Comment by ngirard** [comment]
> Could you try to figure out which branch is being taken there?

Seems to be the 3rd one, twice:
```
2022-01-23T22:17:34.630367Z  INFO winit::platform_impl::platform::x11::util::randr: 3) EnvVarDPI::NotSet    
2022-01-23T22:17:34.630707Z  INFO winit::platform_impl::platform::x11::util::randr: 3) EnvVarDPI::NotSet    
```

**Comment by maroider** [comment]
Ok, then try checking which branch is being taken [here](https://github.com/rust-windowing/winit/blob/0b3902413394f658ef7349d67820db76d56e4c49/src/platform_impl/linux/x11/util/randr.rs#L150-L160). I suspect it's in the `else` block.

**Comment by ngirard** [comment]
Actually it's the other side:
```
2022-01-23T22:22:46.627308Z  INFO winit::platform_impl::platform::x11::util::randr: dpi=0.0    
2022-01-23T22:22:46.627687Z  INFO winit::platform_impl::platform::x11::util::randr: dpi=0.0    
```

**Comment by maroider** [comment]
So it looks like you have a misconfigured `Xft.dpi`. If you haven't set this yourself, then I don't know where else to point you.

This is admittedly something that *could* be made easier to diagnose, but we can't do much in winit to correct this (other than perhaps rejecting 0 as a valid DPI value).

**Comment by ngirard** [comment]
The return value from [here](https://github.com/rust-windowing/winit/blob/0b3902413394f658ef7349d67820db76d56e4c49/src/platform_impl/linux/x11/util/randr.rs#L45) is
```
2022-01-23T22:26:38.549750Z  INFO winit::platform_impl::platform::x11::util::randr: res="*color12:\t#3333bf\n*color4:\t#3465A4\n*customization:\t-color\nXcursor.size:\t24\nXcursor.theme:\tbreeze_cursors\nXft.antialias:\t1\nXft.dpi:\t0\nXft.hinting:\t0\nXft.hintstyle:\thintnone\n"    
2022-01-23T22:26:38.551456Z  INFO winit::platform_impl::platform::x11::util::randr: res="*color12:\t#3333bf\n*color4:\t#3465A4\n*customization:\t-color\nXcursor.size:\t24\nXcursor.theme:\tbreeze_cursors\nXft.antialias:\t1\nXft.dpi:\t0\nXft.hinting:\t0\nXft.hintstyle:\thintnone\n"    
```

**Comment by maroider** [comment]
Yep, `Xft.dpi:\t0` -> `Xft.dpi 0`, that confirms it.

**Comment by ngirard** [comment]
And yet:
```sh
xdpyinfo|rg resolution
  resolution:    96x96 dots per inch
```

**Comment by maroider** [comment]
Winit will try to use whatever is set in `Xft.dpi` *before* manually calculating a scale factor (presumably) in order to allow users to override the DPI.

There is something on your system that's setting a bad value for `Xft.dpi`.

**Comment by ngirard** [comment]
Thanks, I'm on it. It's not `~/.Xresources`. Indeed, `xrdb -query -all|rg dpi` gives `Xft.dpi:        0`, so there must be something else.

**Comment by ngirard** [comment]
Can't find it... Crap !!

**Comment by maroider** [comment]
You *could* try setting `WINIT_X11_SCALE_FACTOR=randr` to get winit to ignore `Xft.dpi`.

**Comment by ngirard** [comment]
I feel like I've looked everywhere and still to no avail. That's extremely frustrating.

> You could try setting WINIT_X11_SCALE_FACTOR=randr to get winit to ignore Xft.dpi.

This works just fine, thanks. I'll stick to that for the moment.

> Winit will try to use whatever is set in Xft.dpi before manually calculating a scale factor (presumably) in order to allow users to override the DPI.

Are we sure this is that we want, given that
> The X _server DPI_ is, on the other hand, barely used. Common GUI toolkits like Qt and GTK don't care about that setting, not even a little. Icons and things like that won't change.
> — [src](https://linuxreviews.org/HOWTO_set_DPI_in_Xorg)

How about having Winit ignore Xft.dpi by default, and take it into account depending on an env. variable ?

**Comment by Imberflur** [comment]
we had a few users report that this assertion failed: https://gitlab.com/veloren/veloren/-/issues/1454
