### ISSUE TITLE
panic on MacOS after dropping EventLoop and creating another

### ISSUE THREAD

**Issue by kcking** [rust-windowing/winit#2282]
I am not sure if this is a supported use-case of winit, but this issue had me scratching my head for a bit and I wanted to at least document it. The panic goes away if we prevent the first event loop from dropping.

The following code re-produces this panic:
```rs
use winit::{event_loop::EventLoop, platform::run_return::EventLoopExtRunReturn, window::Window};

fn main() {
    {
        let mut event_loop = EventLoop::<()>::new();
        let window = Window::new(&event_loop);
        event_loop.run_return(|_, _, c| {
            c.set_exit();
        });
    }
    {
        let mut event_loop = EventLoop::<()>::new();
        let window = Window::new(&event_loop);
        event_loop.run_return(|_, _, c| {
            c.set_exit();
        });
    }
}
```

Example stack trace
```
thread 'main' panicked at 'The panic info must exist here. This failure indicates a developer error.', src/platform_impl/macos/app_state.rs:383:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
   3: core::panicking::panic_str
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:1852:5
   5: core::option::Option<T>::expect
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:715:21
   6: winit::platform_impl::platform::app_state::AppState::cleared
             at ./src/platform_impl/macos/app_state.rs:381:26
   7: winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}
             at ./src/platform_impl/macos/observer.rs:183:21
   8: winit::platform_impl::platform::observer::control_flow_handler::{{closure}}
             at ./src/platform_impl/macos/observer.rs:144:9
   9: std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  10: ___rust_try
  11: std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  12: std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  13: winit::platform_impl::platform::event_loop::stop_app_on_panic
             at ./src/platform_impl/macos/event_loop.rs:259:11
  14: winit::platform_impl::platform::observer::control_flow_handler
             at ./src/platform_impl/macos/observer.rs:142:5
  15: winit::platform_impl::platform::observer::control_flow_end_handler
             at ./src/platform_impl/macos/observer.rs:178:9
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <() as objc::message::MessageArguments>::invoke
             at /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  27: objc::message::platform::send_unverified
             at /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  28: objc::message::send_message
             at /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  29: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
             at ./src/platform_impl/macos/event_loop.rs:216:22
  30: objc::rc::autorelease::autoreleasepool
             at /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/rc/autorelease.rs:29:5
  31: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at ./src/platform_impl/macos/event_loop.rs:206:25
  32: <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return
             at ./src/platform/run_return.rs:61:9
  33: event_loop_lifetime::main
             at ./examples/event_loop_lifetime.rs:14:9
  34: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/platform_impl/macos/event_loop.rs:267:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:752:21
   4: winit::platform_impl::platform::event_loop::stop_app_on_panic
             at ./src/platform_impl/macos/event_loop.rs:267:34
   5: winit::platform_impl::platform::observer::control_flow_handler
             at ./src/platform_impl/macos/observer.rs:142:5
   6: winit::platform_impl::platform::observer::control_flow_end_handler
             at ./src/platform_impl/macos/observer.rs:178:9
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <() as objc::message::MessageArguments>::invoke
             at /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  18: objc::message::platform::send_unverified
             at /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  19: objc::message::send_message
             at /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  20: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
             at ./src/platform_impl/macos/event_loop.rs:216:22
  21: objc::rc::autorelease::autoreleasepool
             at /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/rc/autorelease.rs:29:5
  22: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at ./src/platform_impl/macos/event_loop.rs:206:25
  23: <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return
             at ./src/platform/run_return.rs:61:9
  24: event_loop_lifetime::main
             at ./examples/event_loop_lifetime.rs:14:9
  25: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by madsmtm** [comment]
Nope, trying to create more than one `EventLoop` in general is not supported (not sure if it could be)

**Comment by kcking** [comment]
Ok fair enough, thanks for the quick reply!
