### ISSUE TITLE
`set_fullscreen` should be fallible / crash when setting fullscreen

### ISSUE THREAD

**Issue by martin-t** [rust-windowing/winit#2450]
Currently the function can panic in some (rare) cases. I think it should return a Result instead and let the binary decide whether to crash or not.

For the record the panic i got is this:
```
thread 'main' panicked at 'Failed to change window fullscreen state: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 42, minor_code: 0 }', /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/window.rs:749:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/result.rs:1814:5
   3: winit::platform_impl::platform::x11::window::UnownedWindow::set_fullscreen
   4: winit::platform_impl::platform::x11::window::UnownedWindow::visibility_notify
   5: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::{{closure}}
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/event_processor.rs:539:21
   6: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::with_window::{{closure}}
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/event_processor.rs:73:27
   7: core::option::Option<T>::map
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/option.rs:929:29
   8: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::with_window
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/event_processor.rs:64:22
   9: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/event_processor.rs:538:17
  10: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/mod.rs:517:13
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/mod.rs:348:13
  12: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/mod.rs:448:31
  13: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/x11/mod.rs:503:25
  14: winit::platform_impl::platform::EventLoop<T>::run
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/platform_impl/linux/mod.rs:755:56
  15: winit::event_loop::EventLoop<T>::run
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.2/src/event_loop.rs:278:9
  16: rustcycles::run
  17: rustcycles::main
             at ./src/main.rs:138:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I have no idea what caused it and it only happened once in hundreds of times i started this program. I have a feeling like i might have been alt+tabbing or minimizing a window while this program's window appeared but it happened really fast and i can't reproduce it. I am on Kubuntu 22.04 and i was using `Fullscreen::Borderless(None)`.

**Comment by madsmtm** [comment]
You're probably right - for the record, I think this can fail on macOS as well, though I think we're just ignoring any errors if they do appear

**Comment by kchibisov** [comment]
This doesn't make any sense, since it's misleading. You can't know before hand that the api call can fail and some systems do just ignore the call.

The only reliably way would be to broadcast the changes via some other event like #2334, so you know for sure whether you're in fullscreen or not, since the state change is exposed internally, but not broadcasted.

Right now what we should do is to ignore failures due to such requests.

**Comment by madsmtm** [comment]
Sorry, what @kchibisov said is correct
