### ISSUE TITLE
XWayland compatibility seems busted

### ISSUE THREAD

**Issue by william-worm** [rust-windowing/winit#2783]
Here's something funny I ran into for which I couldn't find an issue.

### Relevant system info
Arch linux running wayland & gnome

Graphics info
```text
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02) (prog-if 00 [VGA controller])
	DeviceName:  Onboard IGD
	Subsystem: Hewlett-Packard Company Device 827e
	Flags: bus master, fast devsel, latency 0, IRQ 131
	Memory at db000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 50000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
```

### Possible steps to reproduce
- Run wayland
- The following code in a project not using bevy/wayland
```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}
```

The problem is resolved by adding wayland as a feature.

### Error Log
```log
2023-05-01T04:50:40.451391Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
2023-05-01T04:50:40.451554Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2023-05-01T04:50:40.501193Z  INFO bevy_render::renderer: AdapterInfo { name: "Mesa Intel(R) HD Graphics 620 (KBL GT2)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
2023-05-01T04:50:40.690291Z ERROR wgpu_core::device: surface configuration failed: incompatible window kind    
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.15.1/src/backend/direct.rs:316:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
thread 'Compute Task Pool (0)' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45thread 'main' panicked at 'A system has panicked so the executor cannot continue.: RecvError', 
/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60
thread '<unnamed>thread '' panicked at 'called `Option::unwrap()` on a `None` valuethread 'Compute Task Pool (0)' panicked at 'internal error: entered unreachable code: sending into a closed channelmain' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:', 459:/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.1/src/task_pool.rs45:
376:49
', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
thread 'Compute Task Pool (0)' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
thread 'main' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45thread '
Compute Task Pool (0)' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
thread 'main' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
thread 'Compute Task Pool (0)' panicked at 'internal error: entered unreachable code: sending into a closed channelthread '', main/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs' panicked at ':internal error: entered unreachable code: sending into a closed channel459', :/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs45:
459:45
thread 'main' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
thread 'Compute Task Pool (1)' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
thread 'Compute Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.10.1/src/pipelined_rendering.rs:136:45
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.1/src/task_pool.rs:376:49
```

**Comment by kchibisov** [comment]
Could you try without wgpu? It works fine with glutin. Also, there's no way to support XWayland explicitly, because it's transparent for us.

**Comment by kchibisov** [comment]
Given that nothing in winit is crashing and your traces are inside the bevy/wgpu, report better to them.
