### ISSUE TITLE
Error "Dynamic loading not supported" on MUSL

### ISSUE THREAD

**Issue by GoodClover** [rust-windowing/winit#3234]
I switched my system over to run Void Linux MUSL recently, and can no longer run winit programs. (They compile fine.)

Someone else running Alpine MUSL [has the same issue](<https://stackoverflow.com/questions/74633209/im-unable-to-run-rust-winit-application-on-alpine-wayland>), so it may be MUSL causing the issue. I use X11 and Void, not Wayland and Alpine.

I really have no clue where to start debugging this, so any guidance would be appreciated.

```
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/mod.rs:787:62:
called `Result::unwrap()` on an `Err` value: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (Dynamic loading not supported); opening library failed (Dynamic loading not supported); opening library failed (Dynamic loading not supported); opening library failed (Dynamic loading not supported)" })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
   4: winit::platform_impl::platform::EventLoop<T>::new
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/mod.rs:787:30
   5: winit::event_loop::EventLoopBuilder<T>::build
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/event_loop.rs:128:25
   6: winit::event_loop::EventLoop<()>::new
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/event_loop.rs:201:9
   7: gam::Display::new
             at ./src/main.rs:21:20
   8: gam::main
             at ./src/main.rs:105:2
   9: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
[with `RUST_BACKTRACE=full`](<http://okturing.com/src/17640/body>)

**Comment by GoodClover** [comment]
Ah I missed #1818, apologies.
