### ISSUE TITLE
Panic on web when opening the print dialog

### ISSUE THREAD

**Issue by danielpeng2** [rust-windowing/winit#3457]
Opening the print dialog in my browser causes a panic with the following error:
```
panicked at /Users/daniel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.7/src/platform_impl/web/web_sys/resize_scaling.rs:129:9:
created media query doesn't match, 1 != 1

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:8000/warp.js:372:21)
    at console_error_panic_hook::hook::h5b803b35d1272057 (http://localhost:8000/warp_bg.wasm:wasm-function[13209]:0x13728f3)
    at core::ops::function::Fn::call::haeda8683ba1f109b (http://localhost:8000/warp_bg.wasm:wasm-function[41289]:0x1854a35)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (http://localhost:8000/warp_bg.wasm:wasm-function[23971]:0x170d30f)
    at std::panicking::begin_panic_handler::{{closure}}::h2f73e4cf6cd6319a (http://localhost:8000/warp_bg.wasm:wasm-function[26553]:0x178b1f6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h98ac61a6abbff7e9 (http://localhost:8000/warp_bg.wasm:wasm-function[41240]:0x185487a)
    at rust_begin_unwind (http://localhost:8000/warp_bg.wasm:wasm-function[29431]:0x17e5e43)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (http://localhost:8000/warp_bg.wasm:wasm-function[31880]:0x18141c2)
    at winit::platform_impl::platform::backend::resize_scaling::ResizeScaleInternal::handle_scale::h8978eb38481975f9 (http://localhost:8000/warp_bg.wasm:wasm-function[5763]:0xe5fab8)
    at winit::platform_impl::platform::backend::media_query_handle::MediaQueryListHandle::new::{{closure}}::h242ce88029eb670c (http://localhost:8000/warp_bg.wasm:wasm-function[31226]:0x1809ff5)
    at <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h708273c9a93a560f (http://localhost:8000/warp_bg.wasm:wasm-function[35039]:0x18371ce)
    at __wbg_adapter_44 (http://localhost:8000/warp.js:233:10)
    at MediaQueryList.real (http://localhost:8000/warp.js:202:20)
```
I'm not sure why the values don't match, since they're both `1`. I've tested on the latest Chrome, Firefox, and Safari versions, and this issue repros in all three.

**Comment by daxpedda** [comment]
I can't seem to reproduce this, would you mind elaborating on how you produced this?
E.g. can you reproduce this with minimal Winit code, or does it only trigger with very specific code in place?

**Comment by danielpeng2** [comment]
I'm only able to trigger it on a specific project I'm working on, I can't create a minimal example that repros.

I noticed that https://github.com/rust-windowing/winit/pull/3371 solves the issue I'm running into. Is there a timeline on when this commit will be included in a release?

**Comment by daxpedda** [comment]
> I'm only able to trigger it on a specific project I'm working on, I can't create a minimal example that repros.

That is unfortunate ...
I'm going to close the issue then as its not really actionable from our side.

> I noticed that #3371 solves the issue I'm running into. Is there a timeline on when this commit will be included in a release?

I will make sure to add it in the next patch release.
Keep in mind though that this will still trigger a panic in debug builds and isn't really a fix as it could cause other bugs inside Winit if this check doesn't succeed.
