### ISSUE TITLE
Outdated err message cites `EventLoopBuilderExtUnix::any_thread`

### ISSUE THREAD

**Issue by Jasha10** [rust-windowing/winit#3488]
Using `egui`+`winit` I got an error message citing `EventLoopBuilderExtUnix::any_thread`. I believe this error message is outdated -- it seems `EventLoopBuilderExtUnix` has been replaced with e.g. `EventLoopBuilderExtX11`.

<details>
<summary>
The error message
</summary>

```
thread '<unnamed>' panicked at /home/homestar/dev/mrepo/src_rs/trading/.vendor/winit/src/platform_impl/linux/mod.rs:747:13:
Initializing the event loop outside of the main thread is a significant cross-platform compatibility hazard. If you absolutely need to create an EventLoop on a different thread, you can use the `EventLoopBuilderExtUnix::any_thread` function.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: winit::platform_impl::platform::EventLoop<T>::new
   3: eframe::native::run::create_event_loop
   4: eframe::native::run::run_glow
   5: eframe::run_native
   6: trading_gui::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

The error message originates from here: https://github.com/rust-windowing/winit/blob/6825fed07379b942e6a8df94f7ee16514d5f7e7c/src/platform_impl/linux/mod.rs#L740-L745

**Comment by Jasha10** [comment]
This comes up e.g. here: https://github.com/emilk/egui/discussions/1489
