### ISSUE TITLE
SSH X11 forwarding seemed to be unsupported

### ISSUE THREAD

**Issue by ztlwk** [rust-windowing/winit#3671]
### Description

Attempting to initialize event loop with ssh x11 forwarding would end up with `NotSupportedError`.

### OS and window mananger

OS: Debian 12
Window manager: kwin

### Winit version

0.30.0

**Comment by notgull** [comment]
Are there any logs in the `tracing` output?

**Comment by ztlwk** [comment]
No, only some stack trace:
```
$ RUST_BACKTRACE=1 DISPLAY=localhost:10 RUST_LOG=trace ./winit-app-example
[2024-05-02T04:02:03Z TRACE winit_app_example] Starting App...
thread 'main' panicked at src/main.rs:34:58:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1073:23
   4: winit_app_example::main
             at /home/smtbook/winit-app-example/src/main.rs:34:19
   5: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
FYI, `glxgears` worked properly.

**Comment by ztlwk** [comment]
No, only some stack trace:
```
$ RUST_BACKTRACE=1 DISPLAY=localhost:10 RUST_LOG=trace ./winit-app-example
[2024-05-02T04:02:03Z TRACE winit_app_example] Starting App...
thread 'main' panicked at src/main.rs:34:58:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1073:23
   4: winit_app_example::main
             at /home/smtbook/winit-app-example/src/main.rs:34:19
   5: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

FYI, `glxgears` worked properly.

**Comment by ztlwk** [comment]
No, only some stack trace:
```
[2024-05-02T04:02:03Z TRACE winit_app_example] Initializing App...
thread 'main' panicked at src/main.rs:34:58:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1073:23
   4: winit_app_example::main
             at /home/testuser/winit-app-example/src/main.rs:34:19
   5: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
FYI, `glxgears` worked properly.

**Comment by ztlwk** [comment]
No, only some back trace:
```
$ RUST_BACKTRACE=1 DISPLAY=localhost:10 RUST_LOG=trace ./winit-app-example
[2024-05-02T04:02:03Z TRACE winit_app_example] Initializing App...
thread 'main' panicked at src/main.rs:34:58:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1073:23
   4: winit_app_example::main
             at /home/testuser/winit-app-example/src/main.rs:34:19
   5: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
FYI, `glxgears` worked properly.

**Comment by ztlwk** [comment]
No, here's the output:
```
$ DISPLAY=localhost:10 RUST_LOG=trace ./winit-app-example
[2024-05-02T04:24:46Z TRACE winit_app_example] Initializing App...
thread 'main' panicked at src/main.rs:34:58:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
FYI, `glxgears` worked properly.

**Comment by notgull** [comment]
Reproduced this issue, standby for investigation.

**Comment by notgull** [comment]
Make sure the following libraries are installed on your remote server:

```
apt install libx11-xcb-dev xinput libxcursor-dev libxkbcommon-x11-dev libx11-dev
```

**Comment by ztlwk** [comment]
Fixed, thanks for the replies.
