### ISSUE TITLE
I tried to run some wgpu examples, but they crash, probably because of winit and fcitx

### ISSUE THREAD

**Issue by Xarizzar** [rust-windowing/winit#3761]
### Description

Hi!

I've been having some issues with winit on my own app, but I can't provide its code at the moment, so I tried running the wgpu example hello triangle in [this repository](https://github.com/gfx-rs/wgpu/tree/trunk/examples), but the program crashed. I was told to make an issue here with some additional information. First, I will post the full backtrace:

```
$ RUST_BACKTRACE=full cargo run --bin wgpu-examples hello_triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.95s
     Running `target/debug/wgpu-examples hello_triangle`
[2024-06-26T08:33:17Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-26T08:33:17Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-26T08:33:17Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-26T08:33:17Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-26T08:33:17Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-26T08:33:17Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
thread 'main' panicked at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/event_processor.rs:1319:18:
Failed to focus input context: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
stack backtrace:
   0:     0x64b684b4ab46 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x64b684b4ab46 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x64b684b4ab46 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x64b684b4ab46 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x64b684b74e90 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x64b684b74e90 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x64b684b4815f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x64b684b4a924 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x64b684b4a924 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x64b684b4be87 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x64b684b4bbe9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x64b684b4c318 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x64b684b4c1f2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x64b684b4b046 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x64b684b4bf50 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x64b68328a145 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x64b68328a783 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x64b683409672 - core::result::Result<T,E>::expect::h2423d13ae0f2a2c8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1030:23
  18:     0x64b6834e014f - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::xinput2_focused::hb261a2ab794b6838
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/event_processor.rs:1317:13
  19:     0x64b6834c79a3 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_xevent::h92b064f9a147f4b4
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/event_processor.rs:239:25
  20:     0x64b683476157 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::h6cbc4365ef7cadd1
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/event_processor.rs:80:9
  21:     0x64b6834173ed - winit::platform_impl::platform::x11::EventLoop<T>::drain_events::he363a2da6528155f
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/mod.rs:626:13
  22:     0x64b68342ed5d - winit::platform_impl::platform::x11::EventLoop<T>::single_iteration::hdba8bf2bc15af39b
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/mod.rs:557:9
  23:     0x64b683414ada - winit::platform_impl::platform::x11::EventLoop<T>::pump_events::ha9c76bb816864a91
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/mod.rs:441:13
  24:     0x64b68341be09 - winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand::h35e71b28b638073e
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/mod.rs:408:19
  25:     0x64b683312ca0 - winit::platform_impl::platform::EventLoop<T>::run_on_demand::heb64ecfa5b006cbd
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:829:56
  26:     0x64b683313c5a - winit::platform_impl::platform::EventLoop<T>::run::hf8ca7ea2e2baec17
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:822:9
  27:     0x64b6833fdbba - winit::event_loop::EventLoop<T>::run::h03743afeb718137d
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/event_loop.rs:249:9
  28:     0x64b683355306 - wgpu_examples::hello_triangle::run::{{closure}}::h3da5491b255676f8
                               at /home/shikigami/Documents/Dev/wgpu-trunk/examples/src/hello_triangle/mod.rs:84:5
  29:     0x64b6832c25f1 - pollster::block_on::h33fc59681546e8a7
                               at /home/shikigami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  30:     0x64b683314d25 - wgpu_examples::hello_triangle::main::h5e55f2048d7281a0
                               at /home/shikigami/Documents/Dev/wgpu-trunk/examples/src/hello_triangle/mod.rs:170:9
  31:     0x64b68328b06f - wgpu_examples::main::h9db9a8ebae53a3be
                               at /home/shikigami/Documents/Dev/wgpu-trunk/examples/src/main.rs:229:5
  32:     0x64b68328b6db - core::ops::function::FnOnce::call_once::h183261fd64a785b4
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  33:     0x64b68328b30e - std::sys_common::backtrace::__rust_begin_short_backtrace::ha6bbac0fc7a11e6c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  34:     0x64b68328b561 - std::rt::lang_start::{{closure}}::h87d201221574240c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  35:     0x64b684b408f1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  36:     0x64b684b408f1 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  37:     0x64b684b408f1 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  38:     0x64b684b408f1 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  39:     0x64b684b408f1 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  40:     0x64b684b408f1 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  41:     0x64b684b408f1 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  42:     0x64b684b408f1 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  43:     0x64b684b408f1 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  44:     0x64b68328b53a - std::rt::lang_start::h49d5f5f8e8c40dd5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  45:     0x64b68328b14e - main
  46:     0x7bf1f3c29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  47:     0x7bf1f3c29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  48:     0x64b68328aa85 - _start
  49:                0x0 - <unknown>
```

Next, my graphics card, Linux kernel, OS, and distribution:
![image](https://github.com/rust-windowing/winit/assets/110132893/7b01640d-07c1-483e-9543-20641dfdfe1b)

One thing to note is, I use fcitx to change keyboard layouts (in general), but when I quit fcitx, the program does not crash, and produces less errors. If there is anything I can do to help, please let me know.

### OS and window mananger

Linux Mint 21.3 Cinnamon on X11

### Winit version

0.29

**Comment by notgull** [comment]
This looks like an issue with Xlib's inbuilt (and rather broken) IME library.

**Comment by notgull** [comment]
cc #3198

**Comment by Xarizzar** [comment]
Hi,

out of curiosity, I was wondering if you could write a detailed explanation as to how you came to that conclusion? I'm not a Linux expert, and I'm not 100% certain how to read these logs, despite everything.

Thank you in advance.

**Comment by notgull** [comment]
The match errors are coming from Xlib's error handling mechanism, and we only use Xlib for a few things nowadays, so it's either:

- OpenGL (unlikely)
- Event handling
- IME
