### ISSUE TITLE
`grab_cursor` on X11 for the same client returns error string if already grabbed

### ISSUE THREAD

**Issue by azriel91** [rust-windowing/winit#639]
Hiya, on X11, when I send in  `win.grab_cursor(true)` to a window on focus, which previously had grabbed and released the cursor, I get back this error:

```rust
Err("Cursor could not be grabbed: already grabbed by another client"),
```

To clarify, it happens when:

1. `win.grab_cursor(true)`
2. `Window::Focused(false); win.grab_cursor(false)`
3. `Window::Focused(true); win.grab_cursor(true)`

I think [this section of code](https://github.com/francesca64/winit/blob/040d3f5d8b0f56e2cbd89e98d7cb4b0b0f83f6d1/src/platform/linux/x11/window.rs#L1086-L1090) is meant to prevent that.

Version of winit I'm using is `0.17.2`.

I haven't got a minimal example (seeing this through one of Amethyst's examples), but can try to make one if necessary.

---

https://github.com/tomaka/winit/issues/591 does mention:

> There's `grab_cursor()` and `hide_cursor()` methods on Window, but no methods to check whether the cursor is hidden or grabbed

> What's the use-case for this?

> Paranoia that someone will ask for it. :-p

that someone is me :stuck_out_tongue:, but I'm not sure if I *should*, in case it's a bug to have the error string returned in the first place.

**Comment by francesca64** [comment]
Sorry for the delay! This definitely looks like a bug in our implementation. A minimal example would be helpful, though it could be a bit before I have access to Linux to try to reproduce this.

**Comment by azriel91** [comment]
That's okay, I too live in a world of multiple urgent things :upside_down_face:!

**Comment by francesca64** [comment]
What WM does this happen on? I've been trying to reproduce with this program:
```rust
extern crate winit;

fn main() {
    let mut event_loop = winit::EventsLoop::new();
    let window = winit::WindowBuilder::new()
        .build(&event_loop)
        .unwrap();
    event_loop.run_forever(|event| {
        if let winit::Event::WindowEvent { event, .. } = event {
            match event {
                winit::WindowEvent::CloseRequested => return winit::ControlFlow::Break,
                winit::WindowEvent::KeyboardInput {
                    input: winit::KeyboardInput {
                        virtual_keycode: Some(winit::VirtualKeyCode::Escape),
                        ..
                    },
                .. } => return winit::ControlFlow::Break,
                winit::WindowEvent::Focused(state) => {
                    window.grab_cursor(state).unwrap();
                },
                _ => (),
            }
        }
        winit::ControlFlow::Continue
    });
}
```
and my results so far:
- Compiz: it doesn't seem possible to unfocus while grabbed.
- KWin, Openbox, Awesome, i3: alt-tabbing/etc. can be used to unfocus, but regrabbing still works fine.

**Comment by azriel91** [comment]
It happens on X, I get this when running the above application and pressing alt + tab twice:

```
$ cargo run              
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/winit_test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Cursor could not be grabbed: already grabbed by another client"', libcore/result.rs:1009:5
```

<details>
<summary>backtrace</summary>

```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /rustc/65204a97d4876b897df0a70c0b9248b57e2bf057/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/65204a97d4876b897df0a70c0b9248b57e2bf057/src/libcore/result.rs:808
  10: winit_test::main::{{closure}}
             at src/main.rs:19
  11: winit::platform::platform::x11::EventsLoop::run_forever::{{closure}}
             at /home/azriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/x11/mod.rs:220
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/65204a97d4876b897df0a70c0b9248b57e2bf057/src/libcore/ops/function.rs:276
  13: winit::platform::platform::x11::EventsLoop::process_event
             at /home/azriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/x11/mod.rs:920
  14: winit::platform::platform::x11::EventsLoop::run_forever
             at /home/azriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/x11/mod.rs:225
  15: winit::platform::platform::EventsLoop::run_forever
             at /home/azriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/mod.rs:501
  16: winit::EventsLoop::run_forever
             at /home/azriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/lib.rs:264
  17: winit_test::main
             at src/main.rs:6
  18: std::rt::lang_start::{{closure}}
             at /rustc/65204a97d4876b897df0a70c0b9248b57e2bf057/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  20: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  21: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:398
             at libstd/rt.rs:58
  22: std::rt::lang_start
             at /rustc/65204a97d4876b897df0a70c0b9248b57e2bf057/src/libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start
```

</details>

My X version:

```bash
$ sudo X -version
[sudo] password for azriel: 

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-138-generic x86_64 Ubuntu
Current Operating System: Linux cerise 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-4.15.0-39-generic root=UUID=71dec35d-4718-487c-a0ca-405c7a603031 ro quiet splash vt.handoff=1
Build Date: 25 October 2018  04:11:27PM
xorg-server 2:1.19.6-1ubuntu4.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

**Comment by francesca64** [comment]
Thanks for confirming the repro works, but it would still help a lot to know which X11 window manager you're using.

**Comment by francesca64** [comment]
Ah, thanks! I've successfully reproduced this in Mutter, so I'll work on a fix.

**Comment by Avokadoen** [comment]
@francesca64 What's the status on this? Grabbing the cursor fails often for me on my fedora laptop :(

```bash
$ printf 'Desktop: %s\nSession: %s\n' "$XDG_CURRENT_DESKTOP" "$GDMSESSION"
Desktop: GNOME
Session: gnome
```

**Comment by Avokadoen** [comment]
Stacktrace:
```
thread 'main' panicked at 'Error grabbing mouse, e: os error at /home/akselhjerpbakk/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/window.rs:1231: Cursor could not be grabbed: grab location not viewable', src/main.rs:76:25
stack backtrace:
   0:     0x5639b5b8dc10 - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5639b5b8dc10 - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5639b5b8dc10 - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5639b5b8dc10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5639b5badbbc - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x5639b5b8a422 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x5639b5b8fde5 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5639b5b8fde5 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5639b5b8fde5 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x5639b5b8f93a - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x5639b5b90581 - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x5639b5b900c7 - std::panicking::begin_panic_handler::{{closure}}::hc552fcee62aad17f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:     0x5639b5b8e0cc - std::sys_common::backtrace::__rust_end_short_backtrace::hb9f0aa9a78e885a0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5639b5b90029 - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:     0x5639b5b8ffdb - std::panicking::begin_panic_fmt::h1b56a0ef7fd4e8be
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:435:5
  15:     0x5639b55d8c0d - tdt4230_raytracer::main::h97bbbd9551cf53f0
                               at /home/akselhjerpbakk/Projects/tdt4230_project_raytracing/src/main.rs:76:25
  16:     0x5639b5626a9b - core::ops::function::FnOnce::call_once::h29f2a4633148e1b1
                               at /home/akselhjerpbakk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  17:     0x5639b55c33be - std::sys_common::backtrace::__rust_begin_short_backtrace::h9c4370769cf4322e
                               at /home/akselhjerpbakk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  18:     0x5639b5634fc1 - std::rt::lang_start::{{closure}}::ha769143dfda1e8b7
                               at /home/akselhjerpbakk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  19:     0x5639b5b909a7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h78040f802d89ccdc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:259:13
  20:     0x5639b5b909a7 - std::panicking::try::do_call::h6853cad536dd09a1
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  21:     0x5639b5b909a7 - std::panicking::try::h827495f03a9fbb9a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  22:     0x5639b5b909a7 - std::panic::catch_unwind::h4bdf17571090eb17
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  23:     0x5639b5b909a7 - std::rt::lang_start_internal::h2f319c33bb013f29
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:51:25
  24:     0x5639b5634f97 - std::rt::lang_start::hd474f43d5a696432
                               at /home/akselhjerpbakk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  25:     0x5639b55d92ba - main
  26:     0x7f9fae9a81e2 - __libc_start_main
  27:     0x5639b55ad10e - _start
  28:                0x0 - <unknown>
  ```

**Comment by francesca64** [comment]
@Avokadoen I think I never figured it out! This was a long time ago, though. I'm not involved in the X11 backend anymore, and after a cursory look through some recent PRs, it looks like there might not be anyone currently maintaining our X11 backend.

Your error looks like it could be a different problem, which would be fortunate, though I don't know enough about how the X11 backend has changed to say for sure. Either way, this is unfortunately all the help I can provide.

**Comment by Avokadoen** [comment]
Ok, thanks for the info. I'll just move towards not panicing when the application fails to grab for now :sweat_smile:. Can't wait for wayland to become default haha
